"""Static layout check for the HUD.

Measures every string the firmware can draw against the box it is drawn into,
using the real TFT_eSPI glyph tables and the real icon dimensions. Run after
any change to src/config.h, src/hud_renderer.cpp or tools/gen_icons.py.
"""
import re

FD = ".pio/libdeps/hosyond-esp32-32e/TFT_eSPI/Fonts/GFXFF/"

ROW = re.compile(r"\s*\{\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,")


BOX = re.compile(r"\s*\{\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,"
                 r"\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)")


def load(name):
    """Return {codepoint: xAdvance} for a TFT_eSPI GFXFF font."""
    adv, grabbing = [], False
    for ln in open(FD + name + ".h"):
        if "Glyphs[]" in ln:
            grabbing = True
            continue
        if grabbing:
            if ln.strip().startswith("};"):
                break
            m = ROW.match(ln)
            if m:
                adv.append(int(m.group(4)))  # 4th field is xAdvance
    # First glyph in these tables is 0x20 (space).
    return {0x20 + i: a for i, a in enumerate(adv)}


def load_boxes(name):
    """Return {codepoint: (height, yOffset)} -- the glyph's vertical extent."""
    out, grabbing, i = {}, False, 0
    for ln in open(FD + name + ".h"):
        if "Glyphs[]" in ln:
            grabbing = True
            continue
        if grabbing:
            if ln.strip().startswith("};"):
                break
            m = BOX.match(ln)
            if m:
                out[0x20 + i] = (int(m.group(3)), int(m.group(6)))
                i += 1
    return out


def load_anton(name):
    """Return {codepoint: xAdvance} for one of the generated Anton faces.

    Same table shape as a TFT_eSPI GFXFF font, but generated by
    tools/gen_anton_font.py into src/hud_font_anton.h rather than shipped with
    the library -- and starting at 0x20 and stopping at 0x5A, because the
    headline face is uppercase only.
    """
    adv, grabbing = [], False
    for ln in open("src/hud_font_anton.h"):
        if name + "Glyphs[]" in ln:
            grabbing = True
            continue
        if grabbing:
            if ln.strip().startswith("};"):
                break
            m = ROW.match(ln)
            if m:
                adv.append(int(m.group(4)))
    return {0x20 + i: a for i, a in enumerate(adv)}


FONTS = {n: load(n) for n in ["FreeSans9pt7b", "FreeSansBold9pt7b",
                              "FreeSansBold12pt7b", "FreeSansBold18pt7b"]}
GLYPH_BOX = {n: load_boxes(n) for n in FONTS}
# After GLYPH_BOX: these two are not in the library's font directory, and only
# their advances are wanted -- the headline face has no descenders to check.
FONTS["Anton16px"] = load_anton("Anton16px")
FONTS["Anton24px"] = load_anton("Anton24px")
# Mirrors src/hud_fonts.h.
BODY, LABEL, VALUE, DISPLAY = ("FreeSans9pt7b", "FreeSansBold9pt7b",
                               "FreeSansBold12pt7b", "FreeSansBold18pt7b")
HEADLINE, HEADLINE_SM = "Anton24px", "Anton16px"

for n, g in FONTS.items():
    print(f"loaded {n}: {len(g)} glyphs")
print()


def w(font, s):
    g = FONTS[font]
    return sum(g.get(ord(c), g[0x20]) for c in s)


# TFT_eSPI's built-in font 1 (setFreeFont(nullptr)): a fixed 5x7 cell plus one
# column of spacing. No table to load -- the advance is the same for every
# character. Used by the strip/bar captions and the footer's sync clock.
GLCD_W, GLCD_H = 6, 8


def glcd(s):
    return GLCD_W * len(s)


def icon_dims(path="src/hud_icons.h"):
    """{icon name: (w, h)} from the generated bitmap header."""
    txt = open(path).read()
    d = {}
    for name, wh, val in re.findall(r"constexpr int16_t (\w+)(W|H) = (\d+);", txt):
        d.setdefault(name, {})[wh] = int(val)
    return {n: (v["W"], v["H"]) for n, v in d.items()}


ICONS = icon_dims()
print("icons: " + ", ".join(f"{n} {w}x{h}" for n, (w, h) in sorted(ICONS.items())))
print()

# --- constants, parsed straight out of src/config.h ---
#
# These used to be re-typed here by hand, "mirrored from src/config.h". They
# drifted: the checker was still validating titleY/targetY/barY/tileY long
# after the card was rebuilt around objY/idyY/ribY/sceneY, so it passed
# against a layout the firmware no longer had. Parsing the header means the
# constants cannot go stale.
def load_config(path="src/config.h"):
    txt = open(path).read()
    out = {}
    for m in re.finditer(r"constexpr int16_t\s+([^;]+);", txt):
        for decl in m.group(1).split(","):
            if "=" not in decl:
                continue
            name, _, val = decl.partition("=")
            name, val = name.strip(), val.strip()
            try:
                out[name] = int(val, 0)
            except ValueError:
                # An expression in terms of names already parsed.
                try:
                    out[name] = int(eval(val, {"__builtins__": {}}, out))
                except Exception:
                    pass
    return out


CFG = load_config()
globals().update(CFG)
print(f"parsed {len(CFG)} layout constants from src/config.h")
print()

badgeMaxW = 175
statY, statH, statGap = 160, 46, 8

# --- derived, mirrored from src/hud_renderer.cpp ---
kTileW = (contentW - 2 * tileGap) // 3   # 142
kStatW = (contentW - statGap) // 2       # 216
kStatInsetX = 12
kTargetNameX = padX + ICONS["target"][0] + targetIconGap
kRewardBoxW = 56

# Mirrors factionIcon() in hud_renderer.cpp. "Humans" is absent there too: the
# SEAF badge is text-only, like an owner with no icon.
FACTION_ICON = {"automaton": "automaton", "terminid": "terminid",
                "illuminate": "illuminate"}


def display_name(faction):
    """Mirrors factionDisplayName() — the badge draws the API's "Humans" as
    "SEAF", so that is the string whose width has to fit."""
    return "SEAF" if faction.lower().startswith("human") else faction


def badge_w(faction):
    bw = w(LABEL, display_name(faction).upper()) + 2 * badgePadX
    for prefix, icon in FACTION_ICON.items():
        if faction.lower().startswith(prefix):
            bw += ICONS[icon][0] + badgeIconGap
            break
    return min(bw, badgeMaxW)


fail = []


def check(label, got, limit):
    ok = got <= limit
    print(f"{'ok ' if ok else 'BAD'} {label:<52} {got:>4}px (limit {limit})")
    if not ok:
        fail.append(label)


def grid(title, bands, top, bottom):
    print(f"=== {title} (rows must not collide) ===")
    prev_name, prev_bottom = "frame top", top
    for name, y, h in bands:
        ok = y >= prev_bottom
        print(f"{'ok ' if ok else 'BAD'} {name:<10} y {y:>3}..{y + h - 1:>3}   "
              f"(after {prev_name} @{prev_bottom})")
        if not ok:
            fail.append(f"row {name} overlaps {prev_name}")
        prev_name, prev_bottom = name, y + h
    check(f"{prev_name} bottom inside the frame", prev_bottom, bottom)
    print()


# The two card layouts. Both open with the header row and close with the same
# stat strip and footer; they differ only in how tall the art is and how many
# tracks sit under it, which is exactly the pair of numbers that has to stay in
# step -- the art absorbing a track's worth of height is what keeps the strip
# on the same row either way.
grid("order card grid", [("header", headerY, headerH), ("rule1", rule1Y, 1),
                         ("art", artY, artOrderH),
                         ("cap1", orderCap1Y, barCapH),
                         ("bar1", orderBar1Y, orderBarH),
                         ("cap2", orderCap2Y, barCapH),
                         ("bar2", orderBar2Y, orderBarH),
                         ("stripCap", stripCapY, stripCapH),
                         ("stripVal", stripValY, stripValH),
                         ("footer", footerY, footerH)],
     frameY + 1, frameY + frameH - 1)

grid("campaign card grid", [("header", headerY, headerH), ("rule1", rule1Y, 1),
                            ("art", artY, artCampH),
                            ("cap", campCapY, barCapH),
                            ("bar", campBarY, campBarH),
                            ("stripCap", stripCapY, stripCapH),
                            ("stripVal", stripValY, stripValH),
                            ("footer", footerY, footerH)],
     frameY + 1, frameY + frameH - 1)

# The combined count card: one band, then a row per target. Its rows are laid
# out at a pitch the renderer computes, so what is asserted here is the band
# and the space the rows are given, and then the pitch bound separately below.
grid("combined count card grid", [("header", headerY, headerH),
                                  ("rule1", rule1Y, 1),
                                  ("band", artY, moCombBandH),
                                  ("rows", moCombRowY,
                                   moCombRowsBot - moCombRowY),
                                  ("footer", footerY, footerH)],
     frameY + 1, frameY + frameH - 1)

print("=== combined count card: the band ===")
# The two text rows inside the band, and the clock plate they have to stop
# short of. The plate rides the band's top corner here rather than its foot,
# which is what frees the whole width for the title/overall row underneath.
kPlateH = plateLabelH + plateClockH + 2 * platePadY
kPlateL = cardX + cardW - plateInset - plateW
check("subject row inside the band", moCombNameDy + moCombNameH, moCombBandH)
check("foot row inside the band", moCombFootDy + moCombFootH, moCombBandH)
check("subject row clear of the foot row", moCombNameDy + moCombNameH,
      moCombFootDy)
check("clock plate inside the band", moCombPlateDy + kPlateH, moCombBandH)
check("subject column clear of the plate", cardX + artPad + 10, kPlateL)
# "100.0% OVERALL" is the widest the overall figure gets: the number is set in
# FONT_VALUE and the word in FONT_LABEL, measured separately by the renderer,
# so they are measured separately here too.
kOverallW = w(VALUE, "100.0%") + moCombPctGap + w(LABEL, "OVERALL")
check('"100.0%" + "OVERALL" inside the card', kOverallW, cardW - 2 * artPad)
# What is left for the order's title once the figure has taken its share. The
# renderer trims to fit, so this only has to be enough for a title to be worth
# printing at all -- an order name is 20-30 characters and this asserts the
# column holds a legible fraction of one, not all of it.
check('"MAJOR ORDER" @9pt bold in the title column', w(LABEL, "MAJOR ORDER"),
      cardW - 2 * artPad - kOverallW - 8)

print("=== combined count card: the target rows ===")
# Four targets is the assignment API's cap (kMaxOrderTasks), so it is the
# tightest the rows ever pack. The renderer centres them at the smaller of
# moCombPitchMax and the space each gets.
MAX_TASKS = 4
kAvailH = moCombRowsBot - moCombRowY
kPitch = min(moCombPitchMax, kAvailH // MAX_TASKS)
print(f"    {kAvailH}px for {MAX_TASKS} rows -> pitch {kPitch}px")
check(f"{MAX_TASKS} rows at their pitch fit the space", MAX_TASKS * kPitch,
      kAvailH)
check("caption and track fit one row's pitch", moCombBarDy + moCombBarH, kPitch)
check("caption row clears the track above it", moCombCapH, moCombBarDy)
# Each row leads with the mark for its target, which has to sit inside the box
# the caption is set in -- the track is 2px under that box and the row above is
# 7px over it, so a mark taller than the box lands on one of them.
check("task mark inside the caption row", ICONS["taskAgitators"][1], moCombCapH)
check("task mark inside its own column", ICONS["taskAgitators"][0], moCombIconW)
# The caption is the built-in 6x8 face and shares its row with the mark ahead
# of it and the percentage column behind it. The widest pair the renderer can
# print at full digits is a billion against a billion, which is what
# formatCompact() exists to fall back from -- so this asserts the fallback is
# reachable, i.e. the compact form always fits.
kCapW = cardW - moCombIconW - moCombIconGap - moCombPctW - moCombPctGap
check("full-digit caption at a realistic goal",
      glcd("ELIMINATED  23,909,079 / 25,000,000"), kCapW)
check("compact caption at the widest goal",
      glcd("ELIMINATED  1.25B / 1.25B"), kCapW)
check('"100.0%" @9pt bold in the percentage column', w(LABEL, "100.0%"),
      moCombPctW)
print()

# The order card's single-track variant (a liberation, or a defence with
# nothing attacking) reuses the taller campaign bar centred in the band the two
# tracks would have filled. It has to stay inside that band, or it collides
# with the strip below.
print("=== order card, single-track variant ===")
check("solo cap after the art", artY + artOrderH, orderSoloCapY)
check("solo track inside the two-track band", orderSoloBarY + campBarH, orderBandEnd)
print()

# Every other screen keeps the plain "SUPER EARTH" strip.
grid("status-screen grid", [("header", headerY, headerH), ("rule1", rule1Y, 1)],
     frameY + 1, frameY + frameH - 1)

# The art band stacks its identity rows inside itself, positioned relative to
# the band's own top, so a collision there does not show up in the grids above.
# The order card is the tighter of the two -- it carries the order title row
# the campaign card does not -- so it is the one worth asserting.
print("=== art band inner rows (order card) ===")
ART_ROWS = [("name", artNameDy, artNameH),
            ("sector", artSectorDy, artSectorH),
            ("headline", artStatDy, artStatH),
            ("orderTitle", artTitleDy, artTitleH)]
prev_name, prev_bottom = "band top", 0
for name, dy, h in ART_ROWS:
    # The rows deliberately overlap by a few px: drawOverText() centres the
    # glyphs in each row, so the boxes touch long before the type does. What
    # matters is that they advance and stay inside the band.
    ok = dy >= prev_bottom - 8
    print(f"{'ok ' if ok else 'BAD'} {name:<10} dy {dy:>3}..{dy + h - 1:>3}   "
          f"(after {prev_name} @{prev_bottom})")
    if not ok:
        fail.append(f"art row {name} overlaps {prev_name}")
    prev_name, prev_bottom = name, dy + h
check("art rows inside the order card's band", prev_bottom, artOrderH)

# The clock plate sits bottom-right of the same band. It must clear the order
# title beside it, which is trimmed against the plate's left edge, and stay
# inside the art.
PLATE_H = plateLabelH + plateClockH + 2 * platePadY
check("clock plate inside the art band",
      (artOrderH - plateInset - PLATE_H) + PLATE_H, artOrderH - 1)
print()

# A text row shorter than the glyphs it actually draws clips them. The bound
# is per-row rather than the font's full line height, because a row that only
# ever sets capitals does not need to reserve descender space -- what matters
# is the span of the characters that row can really contain.
#
# This is the check that would have caught the biome row: 15px for glyphs
# spanning 17px, which cut the baseline row off "DESERT".
print("\n=== text rows vs the glyphs they draw ===")


def glyph_span(font, chars):
    """Total vertical extent, in px, of the tallest/deepest of `chars`."""
    rows = GLYPH_BOX[font]
    top = min(rows[ord(c)][1] for c in chars if ord(c) in rows)
    bot = max(rows[ord(c)][1] + rows[ord(c)][0] for c in chars if ord(c) in rows)
    return bot - top


CAPS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 -,.'%/:"
for label, font, h, chars in [
        ("art sector row", BODY, artSectorH, CAPS),
        ("art headline row", VALUE, artStatH, CAPS),
        ("art order-title row", LABEL, artTitleH, CAPS),
        # The bar/strip caption rows are set in TFT_eSPI's built-in 6x8 GLCD
        # face, which is not a GFX font and has no table to measure; 8px into
        # barCapH/stripCapH is not a bound worth asserting.
        ("strip value row", LABEL, stripValH, CAPS),
        ("clock plate row", LABEL, plateClockH, CAPS),
        ("footer reward row", VALUE, footerH, "0123456789")]:
    need = glyph_span(font, chars)
    ok = h >= need
    print(f"{'ok ' if ok else 'BAD'} {label:<52} {h:>4}px (needs {need})")
    if not ok:
        fail.append(label)
print()

print("\n=== target row: crosshair + planet name + sector tag + badge ===")
print(f"    crosshair {ICONS['target'][0]}x{ICONS['target'][1]} at x={padX}, "
      f"name starts at x={kTargetNameX}")
check("crosshair height in the target row", ICONS["target"][1], targetH)
NAMES = ["X-45", "Meridia", "Hellmire", "Charbal-VII", "Vernen Wells",
         "Angel's Venture", "Heeth", "Mastia"]
SECTORS = ["Ymir", "Andromeda", "Sagittarius"]
for faction in ["Automaton", "Terminids", "Illuminate", "Humans", "Unknown"]:
    bw = badge_w(faction)
    if bw >= badgeMaxW:
        fail.append(f"badge {faction} hits the {badgeMaxW}px cap")
    availW = (contentR - bw - badgeGap) - kTargetNameX
    print(f"  badge {display_name(faction).upper():<11} {bw:>3}px "
          f"-> {availW:>3}px for the name")
    for pn in NAMES:
        g18 = w(DISPLAY, pn)
        used, got = ("18pt", g18) if g18 <= availW else ("12pt", w(VALUE, pn))
        flag = "" if got <= availW else "  <-- OVERFLOW"
        if got > availW:
            fail.append(f"name '{pn}' with {faction}")
        # The sector tag is drawn only when it fits, so it can never overflow;
        # report which combinations keep it.
        tags = [s for s in SECTORS
                if got + tagGap + w(BODY, s.upper()) <= availW]
        print(f"      {pn:<16} {used} {got:>3}px{flag}"
              f"   sector tag kept for {len(tags)}/{len(SECTORS)}")

print("\n=== no-planet fallbacks (target row, full width) ===")
for s in ["PLANET DATA UNAVAILABLE", "GALAXY-WIDE OBJECTIVE"]:
    check(f'"{s}" @12pt', w(VALUE, s), contentR - kTargetNameX)

print("\n=== progress bar label (now at display size) ===")
for pct in [0, 51, 79, 100]:
    check(f'"{pct}% LIBERATED" @18pt', w(DISPLAY, f"{pct}% LIBERATED"), contentW - 2)
check('"AWAITING TELEMETRY" @18pt', w(DISPLAY, "AWAITING TELEMETRY"), contentW - 2)

print("\n=== icon tiles ===")
inner = kTileW - 2 * tileInsetX
print(f"    tile {kTileW}x{tileH} at x=" +
      ", ".join(str(padX + i * (kTileW + tileGap)) for i in range(3)) +
      f", inner width {inner}px")
check("rightmost tile ends inside the content column",
      padX + 2 * (kTileW + tileGap) + kTileW, contentR)
for n in ("clock", "divers", "skull", "check"):
    iw, ih = ICONS[n]
    check(f'tile icon "{n}" width', tileInsetX + iw, kTileW - tileInsetX)
    check(f'tile icon "{n}" height above the value row', tileIconDy + ih, tileValueDy)
check("tile value row inside the tile", tileValueDy + tileValueH, tileH)
# Values are drawn at 12pt and drop to 9pt bold if they don't fit; 9pt is the
# floor, so that is what must fit.
for val in ["18h 22m", "2d 04h", "45m 12s", "EXPIRED", "--", "33.4K", "393.6B",
            "125.4K", "91%", "100%"]:
    g12 = w(VALUE, val)
    used, got = ("12pt", g12) if g12 <= inner else ("9pt", w(LABEL, val))
    check(f'tile value "{val}" @{used}', got, inner)

print("\n=== WiFi setup screen (two-up stat boxes) ===")
sinner = kStatW - 2 * kStatInsetX
for lbl in ["NETWORK", "PASSWORD"]:
    check(f'label "{lbl}" @9pt bold', w(LABEL, lbl), sinner)
for val in ["HD2-Monitor", "helldive"]:
    check(f'value "{val}" @12pt', w(VALUE, val), sinner)

print("\n=== footer (reward at the left, sync clock at the right) ===")
# The reward is the row's headline now, set at 12pt bold in a fixed box so a
# drop from 120 to 45 medals cannot leave the hundreds digit standing.
for r in ["40", "150", "1000"]:
    check(f'reward "{r}" @12pt bold', w(VALUE, r), kRewardBoxW)
check("medal height in the footer row", ICONS["medal"][1], footerH)
# Nothing is drawn between the two blocks, so this is slack, not a tight fit --
# but it is what guarantees a four-digit reward cannot reach the clock.
check("reward block clear of the sync box",
      cardX + ICONS["medal"][0] + footerIconGap + kRewardBoxW,
      contentR - syncBoxW)
# The sync clock: a ring glyph and HH:MM in the built-in 6x8 face, right
# aligned. Staleness is carried by a caption-size prefix as well as the colour
# -- an amber tint alone is not a difference you can name at this size.
for s in ["14:32", "STALE 13:53", "NO DATA"]:
    check(f'clock glyph + "{s}" @6x8', 2 * syncGlyphR + syncGap + glcd(s), syncBoxW)
check("6x8 sync row inside the footer", GLCD_H, footerH)

print("\n=== centred status lines ===")
for s in ["ESTABLISHING UPLINK", "SUPER EARTH", "WIFI SETUP"]:
    check(f'"{s}" @18pt', w(DISPLAY, s), contentW)
check('"NO ACTIVE MAJOR ORDER" @12pt', w(VALUE, "NO ACTIVE MAJOR ORDER"), contentW)
check('"MAJOR ORDER MONITOR" @9pt bold', w(LABEL, "MAJOR ORDER MONITOR"), contentW)
for s in ["Connecting to WiFi...",
          "Synchronising clock...",
          "Contacting High Command...",
          "Setup timed out. Restarting...",
          "Join this network from a phone or laptop,",
          "then set WiFi and UTC offset in the page that opens.",
          "If no page opens, browse to 192.168.4.1"]:
    check(f'"{s[:44]}"', w(BODY, s), contentW)

print("\n=== centrepiece emblem ===")
elw, elh = ICONS["emblemLarge"]
check("emblemLarge width in the content column", elw, contentW)
check("emblemLarge above the idle caption (y=92)", 92 + elh, 146)
check("emblemLarge above the uplink caption (y=96)", 96 + elh, 150)

blw, blh = ICONS["hd2LogoBoot"]
check("hd2LogoBoot width in the content column", blw, contentW)
check("hd2LogoBoot above the boot caption (y=48)", 48 + blh, 232)
check("boot status line inside the frame", 264 + 20, frameY + frameH)

print("\n=== header row (type word, LIBCON chip, carousel pips, MO button, wifi) ===")
# Every word drawStatusHeader() can be handed: the plain strip, the two planet
# objective types, the count-task headers from countWords(), and the plural the
# combined card falls back to when its targets are not all the same kind.
HEADER_WORDS = ["SUPER EARTH", "LIBERATION", "DEFENSE", "OBJECTIVE",
                "EXTRACTION", "ERADICATION", "OPERATIONS", "OBJECTIVES"]
# The row's right-hand limit is the reopen button, not the WiFi slot: the
# button sits between the two, and drawStatusHeader() clears up to its left
# edge for exactly this reason.
for s in HEADER_WORDS:
    check(f'"{s}" @9pt bold in its box', w(LABEL, s), moBtnX - padX)
# The pips are right-aligned on pipRowR now, so what has to clear is the chip
# on their left rather than the WiFi slot on their right. Two page counts are
# reachable and they do not pair with the same words: an order caps the
# carousel at kMaxOrderTasks == 4 pages (a combined count order at 1), and five
# pips only happen with no order at all, when the type word is always
# "LIBERATION".
# "SUPER EARTH" is not in either set: it is the fallback for an empty title,
# which only happens on the screens drawStatusHeader() is called with pages=0
# -- boot, WiFi setup, and the no-data strip. It never shares the row with a
# pip.
CAROUSEL_WORDS = [s for s in HEADER_WORDS if s != "SUPER EARTH"]
for pips, words in ((4, CAROUSEL_WORDS), (5, ["LIBERATION"])):
    rowW = pips * pipS + (pips - 1) * pipGap
    for s in words:
        check(f'chip under "{s}" clear of {pips} right-aligned pips',
              padX + w(LABEL, s) + libconGapX + libconW + pipRowGap,
              pipRowR - rowW)
check("pip row clear of the button", pipRowR + pipGap, moBtnX)
check("active pip inside the header row", pipS, headerH)
check('"OFFLINE" @9pt bold in wifi box',
      w(LABEL, "OFFLINE"), wifiSlotW - (2 * footDotR + 6))

print("\n=== Major Order reopen button ===")
# The button's own box, the emblem inside it, and the clearances either side.
# The emblem is icons::emblemLarge sampled down by an integer 3, so the source
# has to divide cleanly or the bottom row and right column are dropped.
EMB_W, EMB_H = ICONS["emblemLarge"]
check("button inside the header row", moBtnH, headerH)
check("emblem/3 fits the button width", EMB_W // 3, moBtnW - 2)
check("emblem/3 fits the button height", EMB_H // 3, moBtnH - 2)
check("emblem samples at a whole factor (width)", EMB_W % 3, 0)
check("emblem samples at a whole factor (height)", EMB_H % 3, 0)
check("button clear of the WiFi slot", moBtnX + moBtnW + moBtnGap,
      contentR - wifiSlotW)
check("button inside the content column", moBtnX + moBtnW, contentR)
# The tap target is the drawn box grown all round. It may overhang the button
# generously -- nothing else on the panel takes a tap -- but it must stay
# inside the frame, or part of it is unreachable.
check("tap target starts inside the frame", frameX, moBtnHitX)
check("tap target ends inside the frame", moBtnHitX + moBtnHitW,
      frameX + frameW)
check("tap target starts below the frame top", frameY, moBtnHitY)
check("tap target above the first rule", moBtnHitY + moBtnHitH, rule1Y)

print("\n=== faction badge ===")
for n in sorted(set(FACTION_ICON.values())):
    check(f'badge icon "{n}" height', ICONS[n][1], badgeH - 2)
check("badge height in the target row", badgeH, targetH)

# --- the two touch calibration screens --------------------------------------
#
# One card geometry, two colourways: showTouchPrompt() and showTouchSuccess()
# draw the same bands, the same chip, the same icon box and the same five copy
# rows, and differ only in accent, chip mark, icon and strings. So everything
# below is checked once against the geometry and twice against the strings.
#
# These are also the only screens on the HUD set in mixed case, which makes
# them the only ones whose rows have to reserve descender space -- and the
# reason the checks measure the real strings rather than the CAPS alphabet
# everything else uses.
#
# Neither screen draws the HUD frame or the SUPER EARTH strip (the card floats
# on the bridge, as in the reference art), so there is deliberately nothing
# here checking the card against rule1Y or frameY. What bounds it instead is
# the wordmark above and the panel's own bottom edge.
print("\n=== calibration screens: the bridge behind the card ===")
check("wordmark centred", calLogoX, (screenW - calLogoW) // 2)
check("wordmark box clears the card", calLogoY + calLogoH, calCardY)
# The diver overlaps the card's x range and is meant to -- it stands above it,
# not beside it, because there is no margin beside it to stand in. So what has
# to hold is that it stops at the card's top edge, and that it stays out of the
# wordmark's box on its way there.
check("diver box stops at the card's top edge", calDiverY + calDiverH, calCardY)
check("diver box clear of the wordmark", calDiverX + calDiverW, calLogoX)
# drawBridge() keeps its ceiling beam above y=10 precisely so bridgeAt() -- the
# only thing that knows what is behind the wordmark's anti-aliased edges -- can
# answer with space and the planet alone. If the mark ever starts above that,
# its top row blends against a background that is not there.
check("wordmark starts below the ceiling beam", 9, calLogoY)
check("planet's lit limb reaches the top of the panel", calDiscR, calDiscY)

print("\n=== calibration card: bands ===")
calHeadRuleY = calCardY + calHeadH
calBodyY = calHeadRuleY + 1
calStripeY = calCardY + calCardH - calStripeH
grid("calibration card bands", [("head", calCardY + 1, calHeadH - 1),
                                ("headRule", calHeadRuleY, 1),
                                ("body", calBodyY, calStripeY - 1 - calBodyY),
                                ("stripeRule", calStripeY - 1, 1),
                                ("stripes", calStripeY, calStripeH - 1)],
     calCardY, calCardY + calCardH - 1)
check("card bottom inside the panel", calCardY + calCardH, screenH)

print("=== calibration card: body rows ===")
calBodyH = calStripeY - 1 - calBodyY
calTextX = calCardX + calIconInset + calIconS + calTextGap
calTextW = calCardX + calCardW - calTextPadR - calTextX
print(f"    icon {calIconS}x{calIconS} at x={calCardX + calIconInset}, "
      f"text column x={calTextX} w={calTextW}px")
check("icon box inside the body band", calIconS, calBodyH)
check("icon box clear of the text column", calCardX + calIconInset + calIconS,
      calTextX)
CAL_ROWS = [("address", calAddrDy, calAddrH),
            ("copy1", calCopyDy, calLineH),
            ("copy2", calCopyDy + calLineH, calLineH),
            ("copy3", calCopyDy + 2 * calLineH + calParaGap, calLineH),
            ("copy4", calCopyDy + 3 * calLineH + calParaGap, calLineH)]
prev_name, prev_bottom = "body top", 0
for name, dy, h in CAL_ROWS:
    ok = dy >= prev_bottom
    print(f"{'ok ' if ok else 'BAD'} {name:<10} dy {dy:>3}..{dy + h - 1:>3}   "
          f"(after {prev_name} @{prev_bottom})")
    if not ok:
        fail.append(f"cal row {name} overlaps {prev_name}")
    prev_name, prev_bottom = name, dy + h
check("cal text rows inside the body band", prev_bottom, calBodyH)

# TFT_eSPI puts a free font's baseline glyph_ab px below a TL_DATUM anchor
# (drawString() adds glyph_ab and the top datum subtracts nothing), so a row
# clears its own type when baseline + the deepest descender fits inside it.
# That is a different sum from the CAPS rows above, which never descend.
def tl_need(font, s):
    rows = GLYPH_BOX[font]
    ab = max(-yo for _, yo in rows.values())
    bot = max(rows[ord(c)][1] + rows[ord(c)][0] for c in s if ord(c) in rows)
    return ab + bot


print("=== calibration card: strings, both screens ===")
# The salutation row and the four copy rows, for each screen in turn. Every
# string here is one the firmware can actually draw -- showTouchPrompt() and
# showTouchSuccess() in hud_renderer.cpp -- and they are checked as a pair
# because the two share drawCalCopy() and so share every box.
CAL_SCREENS = [
    ("required", "Helldiver,",
     ["This terminal's touch interface is", "not yet calibrated.",
      "Run a calibration to ensure accurate",
      "targeting and stratagem deployment."]),
    ("successful", "Calibration Complete!",
     ["Your touchscreen has been calibrated", "successfully.",
      "Super Earth thanks you for your", "commitment to victory."]),
]
for screen, head, copy in CAL_SCREENS:
    check(f'[{screen}] "{head}" @9pt bold', w(LABEL, head), calTextW)
    check(f'[{screen}] "{head}" row height', tl_need(LABEL, head), calAddrH)
    for s in copy:
        check(f'[{screen}] "{s[:30]}" @9pt', w(BODY, s), calTextW)
        check(f'[{screen}] "{s[:22]}" row height', tl_need(BODY, s), calLineH)

# The header title sits between the chip and the card's right padding. At
# FONT_VALUE the shorter of the two is 394px and does not fit; label weight is
# what makes them. The success screen's is the longer of the pair and so is the
# one that actually sets the floor on the card's width.
calTitleX = calCardX + calBadgeInset + calBadgeW + calTitleGap
calTitleW = calCardX + calCardW - calTextPadR - calTitleX
CAL_TITLES = ["TOUCH CALIBRATION REQUIRED", "TOUCH CALIBRATION SUCCESSFUL"]
for s in CAL_TITLES:
    check(f'"{s}" @9pt bold', w(LABEL, s), calTitleW)

# The hatched band's text plate, and the two lines that sit on it.
print("=== calibration card: the hatched band ===")
check("band text plate inside the card", calBandTextX + calBandTextW,
      calCardX + calCardW - 1)
check("band text plate starts inside the card", calCardX + 1, calBandTextX)
check("band text row inside the band", calBandTextH, calStripeH - 1)
CAL_BAND = ["TOUCH ANYWHERE TO BEGIN", "FOR SUPER EARTH!"]
for s in CAL_BAND:
    check(f'"{s}" @9pt bold', w(LABEL, s), calBandTextW)
# The success screen's wing flashes are measured off "FOR SUPER EARTH!" at
# render time and hang outside it, so the thing that can collide is the card's
# own border rather than the plate -- the plate is wider than the text.
calWingOuter = (calBandTextW // 2 + w(LABEL, "FOR SUPER EARTH!") // 2
                + calMarkGap + calMarkW)
check("band wing flashes inside the card", calBandTextX + calWingOuter,
      calCardX + calCardW - 1)

# The chip's mark is knocked out of the tab's rectangular part, clear of the
# slanted trailing edge -- see the chip block in drawCalCard().
print("=== calibration card: the header chip ===")
check("warning triangle width inside the tab", 23, calBadgeW - calBadgeSlant)
check("warning triangle height inside the tab", calBadgeH - 10, calBadgeH)
check("check disc width inside the tab", 21, calBadgeW - calBadgeSlant)
check("check disc height inside the tab", 21, calBadgeH)
check("chip inside the header band", calBadgeH, calHeadH - 1)

# The medallion, against the box drawCalMedallion() is handed. Unlike the
# reticle -- which is built from the box it is given and cannot outgrow it --
# the medallion is drawn from fixed offsets off the box's top and centre, so
# shrinking calIconS would silently push its rank row out of the card. Its
# crest starts 13px down and its stars are centred at 82 with r=4, so it needs
# 87 of the 92; the wreath is the wider of the two constraints at 2*(19+11).
print("=== calibration card: the body icons ===")
check("medallion crest-to-stars inside its box", 82 + 4 + 1, calIconS)
check("medallion wreath inside its box", 2 * (19 + 11), calIconS)

# --- the uncalibrated hint, in the footer's middle gap -----------------------
#
# Set in the built-in 6x8 face, in the space the footer rework left empty
# between the reward and the sync clock. It has to fit that gap without
# touching either neighbour -- a hint that shoves the reward or the clock is
# worse than no hint.
print("\n=== footer: uncalibrated-touch hint ===")
kHintX = cardX + ICONS["medal"][0] + footerIconGap + kRewardBoxW
kHintW = (contentR - syncBoxW) - kHintX
print(f"    hint box x={kHintX} w={kHintW}px, between the reward and the clock")
check("reward block ends at the hint box's left edge",
      cardX + ICONS["medal"][0] + footerIconGap + kRewardBoxW, kHintX)
check("hint box ends at the sync box's left edge", kHintX + kHintW,
      contentR - syncBoxW)
check('"HOLD SCREEN AT POWER-ON TO CALIBRATE" @6x8',
      glcd("HOLD SCREEN AT POWER-ON TO CALIBRATE"), kHintW)
check("6x8 hint row inside the footer", GLCD_H, footerH)


# --- the three Major Order overlays -----------------------------------------
#
# The one place on this device where the text column is not a rectangle: the
# panel's right edge is a slant, so every row wraps to its own width and every
# plate has to take the narrowest row it spans. Getting that wrong does not
# look like a bug -- it looks like a line of type running into the artwork --
# so the widths are asserted here rather than eyeballed in a preview.
print("\n=== Major Order overlays: the trapezoid text column ===")


def edge_x(y):
    """Mirrors HUDRenderer::overlayEdgeX()."""
    return ovlEdgeTop + (ovlEdgeBot - ovlEdgeTop) * max(0, min(screenH, y)) // screenH


def text_r(y):
    return edge_x(y) - ovlTextPadR


print(f"    column runs {ovlPadX}..{text_r(0)} at the top, "
      f"{ovlPadX}..{text_r(screenH)} at the foot")
check("art plate starts left of the divider's foot", ovlArtX, ovlEdgeBot)
check("divider hairline inside the panel", edge_x(0) + ovlEdgeInk, screenW)

# The header: badge, optional wings, title. Anton is uppercase-only, so these
# are the strings as drawn.
print("=== Major Order overlays: the header row ===")
for kind, title, wings in [("new", "NEW MAJOR ORDER", True),
                           ("success", "MAJOR ORDER SUCCESSFUL", False),
                           ("failure", "MAJOR ORDER FAILED", False)]:
    bx = ovlPadX + (ovlWingW + ovlWingGap if wings else 0)
    tx = bx + ovlBadgeS + (ovlWingGap + ovlWingW if wings else 0) + ovlTitleGap
    check(f'[{kind}] "{title}" @Anton16', w(HEADLINE_SM, title),
          text_r(ovlHdrY + ovlBadgeS // 2) - tx)
    check(f"[{kind}] badge cluster clear of the title", bx + ovlBadgeS, tx)
check("header rule clear of the badge row", ovlHdrY + ovlBadgeS, ovlRuleY)
check("rule tail stays above the header", ovlRuleTail, ovlRuleY - ovlHdrY)

# --- the announcement -------------------------------------------------------
print("=== Major Order announcement: rows ===")
kBriefW = text_r(ovlBriefY + ovlBriefMax * ovlBriefLead) - ovlPadX
print(f"    briefing column {kBriefW}px, {ovlBriefMax} lines at {ovlBriefLead}px")
check("caution stripe clear of the text column", ovlStripeW, ovlPadX)
# 19px is what a 9pt mixed-case row needs once TL_DATUM has put the baseline
# 13px down -- see the note over calCopyDy. A shorter lead repaints the next
# row's opaque background over this row's descenders.
check("briefing lead clears 9pt descenders", 19, ovlBriefLead)
# The briefing pages through the block rather than being cut at its fourth
# line, so the marker row under it is part of the grid now. Its width bound is
# generous -- "24/24" in the 6x8 face is 30px -- but the row's *height* is the
# tight one: it has to fit between the block's last line and the OBJECTIVE
# divider, which the grid below asserts.
check('"24/24" marker in the 6x8 face', glcd("24/24"), ovlBriefPipW)
check("the wrap cap holds a long briefing",
      ovlBriefMax * 6, ovlBriefLinesMax)  # >= 6 pages of four lines
grid("Major Order announcement", [
    ("header", ovlHdrY, ovlBadgeS),
    ("briefing", ovlBriefY, ovlBriefMax * ovlBriefLead),
    ("brief pip", ovlBriefPipY, ovlBriefPipH),
    ("obj rule", ovlObjDivY, ovlDivH),
    ("obj card", ovlObjCardY, ovlObjCardH),
    ("rwd rule", ovlRwdDivY, ovlDivH),
    ("rwd row", ovlRwdRowY, ovlRwdRowH),
    ("foot", ovlFootY, ovlFootH),
], 0, screenH)

kCardR = text_r(ovlObjCardY + ovlObjCardH)
kCardInX = ovlPadX + 12
kCardInW = kCardR - 12 - kCardInX
print("=== Major Order announcement: the objective card ===")
print(f"    card {ovlPadX}..{kCardR}, text column {kCardInW}px")
check("card inside the text column", kCardR, text_r(ovlObjCardY + ovlObjCardH))
check("title rows plus the count fit the card", 3 * ovlObjLead, ovlObjCardH)
check('"12 OBJECTIVES" @9pt', w(BODY, "12 OBJECTIVES"), kCardInW)
# The reward line is the widest of the two the renderer can pick.
kRwdR = text_r(ovlRwdRowY + ovlRwdRowH)
kRwdX = ovlPadX + 12 + ICONS["medal"][0] + 10
check('"NOT YET POSTED" @9pt bold', w(LABEL, "NOT YET POSTED"), kRwdR - 1 - kRwdX)
check('"1000000 MEDALS" @9pt bold', w(LABEL, "1000000 MEDALS"), kRwdR - 1 - kRwdX)
check("medal chip inside the reward row", ICONS["medal"][1], ovlRwdRowH - 2)
check('"TOUCH TO DISMISS" @9pt bold', w(LABEL, "TOUCH TO DISMISS"),
      text_r(ovlFootY + ovlFootH) - (ovlPadX + 26))

# --- the verdicts -----------------------------------------------------------
print("=== Major Order verdicts: rows ===")
check("prose lead clears 9pt descenders", 19, ovlVerdLead)
check("accent row clears 9pt descenders", 19, ovlVerdAccentH)
grid("Major Order verdict", [
    ("header", ovlHdrY, ovlBadgeS),
    ("prose", ovlVerdProseY, 3 * ovlVerdLead),
    ("accent", ovlVerdAccentY, ovlVerdAccentH),
    ("stats", ovlVerdStatY, 2 * ovlVerdStatH),
    ("stars", ovlVerdStarY - ovlVerdStarR, 2 * ovlVerdStarR),
    ("dismiss", ovlVerdDismissY, ovlVerdDismissH),
    ("band", screenH - ovlBandH, ovlBandH),
], 0, screenH)

kVerdStatW = text_r(ovlVerdStatY + 2 * ovlVerdStatH) - ovlPadX
check('"Liberty prevails. Well done." @9pt',
      w(BODY, "Liberty prevails. Well done."),
      text_r(ovlVerdAccentY + ovlVerdAccentH) - ovlPadX)
check('"Super Earth endures." @9pt', w(BODY, "Super Earth endures."),
      text_r(ovlVerdAccentY + ovlVerdAccentH) - ovlPadX)
check('"12/12 OBJECTIVES MET" @9pt', w(BODY, "12/12 OBJECTIVES MET"), kVerdStatW)
check('"+1000000 MEDALS" @9pt', w(BODY, "+1000000 MEDALS"), kVerdStatW)
check('"TOUCH TO DISMISS" @9pt bold [verdict]', w(LABEL, "TOUCH TO DISMISS"),
      text_r(ovlVerdDismissY + ovlVerdDismissH) - ovlPadX)
# Five stars between two bar flashes, centred in the column.
kStarCx = (ovlPadX + text_r(ovlVerdStarY)) // 2
check("star row plus its flashes inside the column",
      kStarCx + 2 * ovlVerdStarGap + ovlVerdStarR + 8 + 18, text_r(ovlVerdStarY))
check("star row plus its flashes clear of the margin", ovlPadX,
      kStarCx - 2 * ovlVerdStarGap - ovlVerdStarR - 8 - 18)
check("hatched band inside the panel", edge_x(screenH - 1) - 1, edge_x(screenH - 1))

print("\n" + ("ALL LAYOUT CHECKS PASSED" if not fail else "FAILURES:\n  " + "\n  ".join(fail)))
