#!/usr/bin/env python3
"""Generates src/hud_audio_clip.h from tools/assets/hellpods_source.mp3.

The board plays audio out of the ESP32's internal 8-bit DAC (see
src/hud_audio.h), so the clip has to land as 8-bit unsigned PCM in PROGMEM.
Flash is the binding constraint on this project -- the image already sits at
~95% of its OTA slot -- so the pipeline is built around spending as few bytes
as possible while keeping speech intelligible on a small cone:

  decode + downsample to 8 kHz mono  (afconvert, macOS built-in)
    -> trim leading/trailing silence  (the source has ~0.5s of it)
    -> normalise                      (source peaks at ~53% of full scale)
    -> quantise to 8-bit unsigned     (1 byte per sample)

8 kHz is telephone bandwidth. It is the lowest rate that still carries a
shouted line clearly, and at 1 byte/sample it costs 8 KB per second -- 16 kHz
would double that for a difference this speaker cannot reproduce anyway.

Usage:  python3 tools/gen_audio_clip.py [--preview]
"""
import os
import struct
import subprocess
import sys
import tempfile
import wave

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "assets", "hellpods_source.mp3")
OUT = os.path.join(ROOT, "src", "hud_audio_clip.h")

SAMPLE_RATE = 8000
# Silence gate for trimming, as a fraction of full scale. Low enough to keep
# the attack of the first word, high enough to skip the encoder's lead-in.
TRIM_THRESHOLD = 0.02
# Headroom below full scale after normalising. The DAC feeds an amplifier
# that is happier not being asked for the last few percent.
PEAK_TARGET = 0.90


def decode_to_wav(src, dst):
    """mp3 -> 8 kHz mono 16-bit WAV, via macOS's afconvert."""
    subprocess.run(
        ["afconvert", "-f", "WAVE", "-d", "LEI16@%d" % SAMPLE_RATE, "-c", "1", src, dst],
        check=True,
    )


def load_samples(path):
    with wave.open(path) as w:
        assert w.getnchannels() == 1, "expected mono"
        assert w.getframerate() == SAMPLE_RATE, "expected %d Hz" % SAMPLE_RATE
        n = w.getnframes()
        return list(struct.unpack("<%dh" % n, w.readframes(n)))


def trim(samples):
    gate = 32768 * TRIM_THRESHOLD
    first = next((i for i, v in enumerate(samples) if abs(v) > gate), 0)
    last = next((i for i in range(len(samples) - 1, -1, -1) if abs(samples[i]) > gate),
                len(samples) - 1)
    return samples[first:last + 1]


def to_u8(samples):
    peak = max((abs(v) for v in samples), default=1) or 1
    gain = (32767 * PEAK_TARGET) / peak
    out = bytearray()
    for v in samples:
        s = int(v * gain)
        s = -32768 if s < -32768 else (32767 if s > 32767 else s)
        # 16-bit signed -> 8-bit unsigned, centred on 128 (audio::kDacIdle).
        out.append((s + 32768) >> 8)
    return out, gain


def emit(pcm, path):
    lines = [
        "// Generated by tools/gen_audio_clip.py -- do not edit by hand.",
        "//",
        "// 8-bit unsigned PCM, %d Hz mono, %d samples (%.2f s)." % (
            SAMPLE_RATE, len(pcm), len(pcm) / SAMPLE_RATE),
        "// Source: tools/assets/hellpods_source.mp3",
        "//",
        "// Played through the board's DAC by audio::playPcm8(); see",
        "// src/hud_audio.h for the pin assignment and why playback blocks.",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "#include <pgmspace.h>",
        "",
        "namespace audioclip {",
        "",
        "static const uint32_t kSampleRate = %d;" % SAMPLE_RATE,
        "static const size_t kHellpodsLen = %d;" % len(pcm),
        "",
        "static const uint8_t hellpods[] PROGMEM = {",
    ]
    for i in range(0, len(pcm), 16):
        chunk = pcm[i:i + 16]
        lines.append("    " + " ".join("0x%02X," % b for b in chunk))
    lines += ["};", "", "}  // namespace audioclip", ""]

    with open(path, "w") as f:
        f.write("\n".join(lines))


def main():
    if not os.path.exists(SRC):
        sys.exit("missing source: %s" % SRC)

    with tempfile.TemporaryDirectory() as tmp:
        wav = os.path.join(tmp, "clip.wav")
        decode_to_wav(SRC, wav)
        raw = load_samples(wav)

    trimmed = trim(raw)
    pcm, gain = to_u8(trimmed)

    emit(pcm, OUT)
    print("source     %.2f s (%d samples)" % (len(raw) / SAMPLE_RATE, len(raw)))
    print("trimmed    %.2f s (%d samples)" % (len(trimmed) / SAMPLE_RATE, len(trimmed)))
    print("gain       x%.2f" % gain)
    print("wrote      %s  (%d bytes of PROGMEM, %.1f KB)" %
          (os.path.relpath(OUT, ROOT), len(pcm), len(pcm) / 1024.0))

    if "--preview" in sys.argv:
        # Coarse waveform, so a bad trim/normalise is visible without a flash.
        cols = 72
        step = max(1, len(pcm) // cols)
        bars = " .:-=+*#%@"
        row = ""
        for i in range(0, len(pcm), step):
            window = pcm[i:i + step]
            amp = max(abs(int(b) - 128) for b in window) / 128.0
            row += bars[min(len(bars) - 1, int(amp * len(bars)))]
        print("\n" + row)


if __name__ == "__main__":
    main()
