"""Generate the biome backdrop strips in src/hud_biomes.h.

The campaign screen draws a photograph of the planet's terrain behind its
readout. The art is the community companion app's biome set
(tools/assets/biomes/*.webp), reduced to RGB565.

Stored at half the drawn size and scaled up on the device: at full 440x88 the
set is 1.3 MB, which does not fit beside the firmware, while 220x44 is 662 KB
and does. The renderer already owns the scaler this needs -- srcCoord() and
lerp565(), the same pair that blows up the Earth wash in hud_header_art.h -- so
upscaling costs code that already exists.

    python3 tools/gen_biomes.py            # rewrite the header
    python3 tools/gen_biomes.py --preview  # also dump the slug table
"""
import argparse
import glob
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(HERE, "assets", "biomes")
OUT_H = os.path.join(HERE, "..", "src", "hud_biomes.h")

# Stored size. Drawn at 2x this, so keep the aspect at the band's 5:1-ish.
W, H = 220, 44

# The panel is dim and the readout sits on top, so the plate is darkened here
# rather than at draw time -- one multiply in Python beats one per pixel per
# repaint on the ESP32.
DIM = 0.55

# Plates no runtime path can reach. biomeFromName() in src/hd2_model.h is the
# only thing that indexes the table, and it never returns these -- the API
# names them nothing it matches (the three extra black holes and the three
# extra glaciers each collapse onto their _base plate, and the two tutorial
# biomes are not in the live war). Each one is 19,360 B of a flash slot that
# has ~25 KB spare, so they are skipped rather than shipped. The source .webp
# files stay in tools/assets/biomes -- if the API ever starts naming one of
# these, add the match to biomeFromName() and drop the slug from here.
UNREACHABLE = {
    "blackhole1",
    "blackhole2",
    "blackhole_conventional",
    "glacier_bot",
    "glacier_coldrocky",
    "glacier_tienkwan",
    "primordial_tutorial",
    "sandy_tutorial",
}


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def reduce_biome(path):
    im = Image.open(path).convert("RGB")
    # Crop to the band's aspect before scaling so the horizon is not squashed.
    target = W / H
    w, h = im.size
    if w / h > target:
        new_w = int(h * target)
        im = im.crop(((w - new_w) // 2, 0, (w - new_w) // 2 + new_w, h))
    else:
        new_h = int(w / target)
        im = im.crop((0, (h - new_h) // 2, w, (h - new_h) // 2 + new_h))
    im = im.resize((W, H), Image.LANCZOS)

    px = im.load()
    for y in range(H):
        for x in range(W):
            r, g, b = px[x, y]
            px[x, y] = (int(r * DIM), int(g * DIM), int(b * DIM))
    return im


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", action="store_true")
    args = ap.parse_args()

    slugs = sorted(os.path.splitext(os.path.basename(p))[0]
                   for p in glob.glob(os.path.join(SRC_DIR, "*.webp")))
    skipped = [s for s in slugs if s in UNREACHABLE]
    slugs = [s for s in slugs if s not in UNREACHABLE]
    imgs = [(s, reduce_biome(os.path.join(SRC_DIR, s + ".webp"))) for s in slugs]

    with open(OUT_H, "w") as f:
        f.write("// Generated by tools/gen_biomes.py -- do not edit by hand.\n")
        f.write("//\n")
        f.write("// Biome backdrops for the campaign screen, RGB565, already\n")
        f.write("// darkened so the readout stays legible on top. Stored at\n")
        f.write(f"// {W}x{H} and drawn at 2x -- the full-size set does not fit.\n")
        f.write("#pragma once\n\n#include <Arduino.h>\n\n")
        f.write("namespace biomes {\n\n")
        f.write(f"constexpr int16_t kW = {W};\n")
        f.write(f"constexpr int16_t kH = {H};\n")
        f.write(f"constexpr int16_t kCount = {len(imgs)};\n\n")

        for slug, im in imgs:
            px = im.load()
            f.write(f"static const uint16_t {slug}[] PROGMEM = {{\n")
            for y in range(H):
                row = ",".join(f"0x{rgb565(*px[x, y]):04X}" for x in range(W))
                f.write(row + ",\n")
            f.write("};\n\n")

        f.write("// Indexed by BiomeKind in hd2_model.h.\n")
        f.write("static const uint16_t *const table[kCount] PROGMEM = {\n")
        for slug, _ in imgs:
            f.write(f"    {slug},\n")
        f.write("};\n\n")
        f.write("}  // namespace biomes\n")

    total = len(imgs) * W * H * 2
    print(f"wrote src/hud_biomes.h  ({len(imgs)} biomes, {total / 1024:.0f} KB)")
    if skipped:
        print(f"  skipped {len(skipped)} unreachable: {', '.join(skipped)}")
    if args.preview:
        for i, (slug, _) in enumerate(imgs):
            print(f"  {i:>2}  {slug}")


if __name__ == "__main__":
    main()
