"""Generate the Major Order overlay art plate in src/hud_mo_art.h.

The three event overlays -- new order, success, failure -- are set against the
photograph from Cody's reference art (mo_new_reference.jpg): the Super Earth
flag on its pole, the orbital city under it, the planet limb and the star
field behind. The composition puts it down the right-hand side of the panel,
behind an angled divider.

One plate, three screens. The references show three different photographs --
a blue night for the announcement, a brighter sky for the success, a burning
red one with a shredded flag for the failure -- and there is not room in the
app slot for three (see the arithmetic below). So this emits the announcement
frame only and the renderer grades it per screen: drawOverlayArt() in
hud_renderer.cpp desaturates toward red and lifts an ember glow off the
skyline for a failure, and cools and lifts the whole frame for a success.

Sizing, the same trade tools/gen_biomes.py makes: the plate is drawn at
240x320 (half the panel, the art side of the divider) and stored at half that
in each axis, then scaled back up by the renderer's existing bilinear pair
srcCoord()/lerp565(). Full size is 240*320*2 = 153,600 B against 66,939 B of
free app slot, and does not fit. Half is 120*160*2 = 38,400 B and does, with
28 KB left for the code that draws it.

    python3 tools/gen_mo_art.py
"""
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "mo_new_reference.jpg")
OUT_H = os.path.join(HERE, "..", "src", "hud_mo_art.h")

# Stored size. Drawn at 2x this; keep the 3:4 aspect of the art side of the
# panel (ovlArtW x screenH in config.h).
W, H = 120, 160

# The cut taken out of the reference. The reference card is 1179x620 with the
# text panel over its left third, so the art starts around x=460; this crops
# in further to x=630 to put the flagpole a third of the way across a portrait
# frame rather than at its edge, and keeps the full height so the city stays
# under the flag the way the reference has it.
CROP = (630, 0, 1095, 620)


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main():
    im = Image.open(SRC).convert("RGB").crop(CROP)
    im = im.resize((W, H), Image.LANCZOS)

    px = im.load()
    with open(OUT_H, "w") as f:
        f.write("// Generated by tools/gen_mo_art.py -- do not edit by hand.\n")
        f.write("//\n")
        f.write("// The Major Order overlay art plate: the Super Earth flag, the\n")
        f.write("// orbital city and the star field, cut from mo_new_reference.jpg.\n")
        f.write(f"// RGB565, stored {W}x{H} and drawn at 2x -- full size does not\n")
        f.write("// fit the app slot. One plate serves all three overlays; the\n")
        f.write("// renderer grades it per screen. See the generator for both.\n")
        f.write("#pragma once\n\n#include <Arduino.h>\n\n")
        f.write("namespace moart {\n\n")
        f.write(f"constexpr int16_t kW = {W};\n")
        f.write(f"constexpr int16_t kH = {H};\n\n")
        f.write("static const uint16_t flag[] PROGMEM = {\n")
        for y in range(H):
            f.write(",".join(f"0x{rgb565(*px[x, y]):04X}" for x in range(W)) + ",\n")
        f.write("};\n\n")
        f.write("}  // namespace moart\n")

    print(f"wrote src/hud_mo_art.h  ({W}x{H}, {W * H * 2:,} B)")


if __name__ == "__main__":
    main()
