"""Generate the one-day AI bulletin overlay art in src/hud_bulletin_art.h.

A one-off. Cody had a fake "HELLDIVERS 2 MAJOR ORDER BULLETIN" card generated
-- Anthropic funding bill passed, AI goes self-aware at 02:14 -- and it takes
the whole panel on 2026-08-29 and never again. Unlike the three Major Order
overlays this is not a plate the renderer composes a layout around: the card
is already a finished bulletin, header bar and footer rule and all, so it is
drawn full-bleed at 480x320 with nothing but the dismissal hint over it.

Sizing, same trade tools/gen_mo_art.py and tools/gen_biomes.py make: store
small, scale up on the device through the renderer's existing bilinear pair
srcCoord()/lerp565(). The arithmetic is different here only because the plate
has to cover the whole panel rather than the 240x320 art side of a divider:
480*320*2 = 307,200 B against 199,195 B of free app slot on the build this was
cut from, so full size is not an option and the question is only how far down.
Half, the figure gen_mo_art settled on, is 240*160*2 = 76,800 B and fits
easily, but at 2x the card's small type -- the event timeline, the timestamps
-- goes to mush, and that fine print is half of what makes the gag land.
300x200 is 120,000 B, reads the timeline rows as text, and still leaves ~79 KB
(3.9% of the slot) after the code that draws it. 360x240 is barely sharper and
leaves 26 KB, which is not a margin.

The crop takes the card's native 1179x813 (~1.45:1) to the panel's 3:2. That
costs 27 rows, and which 27 is the whole decision: the card carries only ~22
rows of black above its frame and ~23 below, and the dismissal hint has to sit
somewhere that is not on top of the card's own text. So the window is slid all
the way down -- (0, 27) to (1179, 813) -- spending the top margin and the
frame's top border line, which full-bleed art does not miss, to keep the
bottom margin on the panel as the ~13 px black strip the hint is drawn into.
See drawBulletinOverlay() in hud_renderer.cpp for the other half of that.

    python3 tools/gen_bulletin_art.py
"""
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "assets", "ai_bulletin_source.jpg")
OUT_H = os.path.join(HERE, "..", "src", "hud_bulletin_art.h")

# Stored size. Drawn at 480x320 -- 1.6x, not the integer 2x gen_mo_art uses;
# srcCoord() is a general rescale and does not care.
W, H = 300, 200

# Slid to the bottom of the 813-row source, for the black strip. See above.
CROP = (0, 27, 1179, 813)


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main():
    im = Image.open(SRC).convert("RGB").crop(CROP)
    cw, ch = im.size
    assert abs(cw / ch - 1.5) < 0.005, f"crop {cw}x{ch} is not 3:2"
    im = im.resize((W, H), Image.LANCZOS)

    px = im.load()
    with open(OUT_H, "w") as f:
        f.write("// Generated by tools/gen_bulletin_art.py -- do not edit by hand.\n")
        f.write("//\n")
        f.write("// The one-day AI bulletin overlay: Cody's fake MAJOR ORDER\n")
        f.write("// BULLETIN card, cut from tools/assets/ai_bulletin_source.jpg.\n")
        f.write(f"// RGB565, stored {W}x{H} and drawn full-bleed at 480x320 --\n")
        f.write("// full size is 307,200 B and does not fit the app slot. See the\n")
        f.write("// generator for the sizing and the crop.\n")
        f.write("#pragma once\n\n#include <Arduino.h>\n\n")
        f.write("namespace bulletinart {\n\n")
        f.write(f"constexpr int16_t kW = {W};\n")
        f.write(f"constexpr int16_t kH = {H};\n\n")
        f.write("static const uint16_t card[] PROGMEM = {\n")
        for y in range(H):
            f.write(",".join(f"0x{rgb565(*px[x, y]):04X}" for x in range(W)) + ",\n")
        f.write("};\n\n")
        f.write("}  // namespace bulletinart\n")

    print(f"wrote src/hud_bulletin_art.h  ({W}x{H}, {W * H * 2:,} B)")


if __name__ == "__main__":
    main()
