"""Generate the full-colour faction badge icons in src/hud_faction_icons.h.

These are the only faction art in the project that is *not* a 1-bit mask. The
official insignia carry their meaning in a tonal split — a lighter facet over a
darker body — and the Illuminate mark in particular collapses to a featureless
blob when reduced to one bit at badge size. So these three are stored as RGB565
and blitted with TFT_eSPI::pushImage(), the same route src/hud_header_art.h
already uses for the Earth wash.

Source art is the official vector artwork, rasterised to
tools/assets/faction_*_source.png. As with the crest and the SEAF emblem, the
icons are reduced from that art rather than redrawn as approximate geometry.

RGB565 has no alpha, so transparency rides on a key colour: any pixel the art
does not cover is emitted as kTransparent and skipped by pushImage(). That
matters because these icons are not only drawn on theme::bg — the invasion
ribbon puts one on a red hazard fill, where a baked-in background reads as a
black box around the mark.

Edges are cut hard at 50% coverage rather than blended, since a single key
colour cannot carry partial alpha and blending toward any one background would
fringe against the others. At badge size that matches the hard-edged 1-bit
icons the rest of the HUD uses.

    python3 tools/gen_faction_icons.py            # rewrite the header
    python3 tools/gen_faction_icons.py --preview  # also dump each icon's size
"""
import argparse
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "..", "src", "hud_faction_icons.h")

# Transparency key. Magenta, which appears nowhere in the three insignia, so it
# can never collide with real artwork. Must match facicons::kTransparent.
KEY = 0xF81F

# Coverage at or above which a pixel counts as part of the mark.
ALPHA_CUT = 128

# Badge slot. 20x20 matches the 1-bit faction icons this replaces, so nothing
# in `namespace layout` has to move.
SLOT = 20

ICONS = [
    ("automaton", "faction_automaton_source.png"),
    ("terminid", "faction_terminid_source.png"),
    ("illuminate", "faction_illuminate_source.png"),
]


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def reduce_icon(path, slot=SLOT):
    """Letterbox the source art into the slot, keeping its alpha.

    The art keeps its own aspect ratio rather than being stretched to the
    slot — same rule as mask_fit() in gen_icons.py.
    """
    src = Image.open(path).convert("RGBA")
    bbox = src.split()[3].point(lambda p: 255 if p > 8 else 0).getbbox()
    if bbox:
        src = src.crop(bbox)

    scale = min(slot / src.width, slot / src.height)
    w, h = max(1, round(src.width * scale)), max(1, round(src.height * scale))
    src = src.resize((w, h), Image.LANCZOS)

    canvas = Image.new("RGBA", (slot, slot), (0, 0, 0, 0))
    canvas.paste(src, ((slot - w) // 2, (slot - h) // 2))
    return canvas


def emit(f, name, img):
    px = img.load()
    f.write(f"constexpr int16_t {name}W = {img.width};\n")
    f.write(f"constexpr int16_t {name}H = {img.height};\n")
    f.write(f"static const uint16_t {name}[] PROGMEM = {{\n")
    for y in range(img.height):
        cells = []
        for x in range(img.width):
            r, g, b, a = px[x, y]
            cells.append(f"0x{KEY:04X}" if a < ALPHA_CUT else f"0x{rgb565(r, g, b):04X}")
        f.write("    " + ", ".join(cells) + ",\n")
    f.write("};\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", action="store_true")
    args = ap.parse_args()

    imgs = [(n, reduce_icon(os.path.join(HERE, "assets", src))) for n, src in ICONS]

    with open(OUT_H, "w") as f:
        f.write("// Generated by tools/gen_faction_icons.py -- do not edit by hand.\n")
        f.write("//\n")
        f.write("// Full-colour faction insignia, RGB565, drawn with pushImage().\n")
        f.write("// Unlike src/hud_icons.h these are not 1-bit masks and are not\n")
        f.write("// tinted by the caller: the colour is the artwork's own.\n")
        f.write("// Pixels equal to kTransparent are skipped, so these are safe to\n")
        f.write("// draw over any background.\n")
        f.write("#pragma once\n\n")
        f.write("#include <Arduino.h>\n\n")
        f.write("namespace facicons {\n\n")
        f.write("// Key colour meaning 'leave this pixel alone'. Magenta appears\n")
        f.write("// nowhere in the artwork, so it cannot collide with real pixels.\n")
        f.write(f"constexpr uint16_t kTransparent = 0x{KEY:04X};\n\n")
        for name, img in imgs:
            emit(f, name, img)
        f.write("}  // namespace facicons\n")

    total = sum(i.width * i.height * 2 for _, i in imgs)
    print(f"wrote {os.path.relpath(OUT_H, os.path.dirname(HERE))}"
          f"  ({len(imgs)} icons, {total} bytes)")
    if args.preview:
        for name, img in imgs:
            print(f"  {name:<12} {img.width}x{img.height}  "
                  f"{img.width * img.height * 2} B")


if __name__ == "__main__":
    main()
