#include "hud_renderer.h"

#include "config.h"
#include "hd2_api.h"   // formatDuration / formatCompact
#include "hud_fonts.h" // must be included by exactly one .cpp
#include "hud_icons.h" // generated by tools/gen_icons.py
#include "hud_header_art.h" // generated by tools/gen_header_art.py
#include "hud_faction_icons.h" // generated by tools/gen_faction_icons.py
#include "hud_biomes.h" // generated by tools/gen_biomes.py

using namespace layout;

// ---------------------------------------------------------------------------
//  Icons
// ---------------------------------------------------------------------------

namespace {

struct IconRef {
  const uint8_t *bits;
  int16_t w, h;
};

// A full-colour icon. `px` is RGB565 blitted with pushImage() rather than
// tinted; pixels equal to facicons::kTransparent are left alone, so one of
// these can sit on the alert ribbon as safely as on the panel background.
struct ColorIconRef {
  const uint16_t *px;
  int16_t w, h;
};

// The badge icon for a planet owner. Matched on a lowercased prefix so both
// the singular and plural spellings the API uses ("Automaton", "Terminids")
// land on the same icon.
//
// These three are full-colour RGB565, not 1-bit masks: the official insignia
// read as a lighter facet over a darker body, and that split is the whole
// identity of the Illuminate mark in particular -- reduced to one bit at badge
// size it is a featureless blob. They carry their own colour and are not
// tinted by the caller. See src/hud_faction_icons.h.
//
// There is deliberately no entry for "Humans": the SEAF emblem's detail does
// not survive the reduction to a badge-sized bitmap, so that badge takes the
// same text-only route as an owner we have no icon for at all.
ColorIconRef factionIcon(const String &faction) {
  String f = faction;
  f.toLowerCase();
  if (f.startsWith("automaton"))
    return {facicons::automaton, facicons::automatonW, facicons::automatonH};
  if (f.startsWith("terminid"))
    return {facicons::terminid, facicons::terminidW, facicons::terminidH};
  if (f.startsWith("illuminate"))
    return {facicons::illuminate, facicons::illuminateW, facicons::illuminateH};
  return {nullptr, 0, 0};  // SEAF / unknown owner: badge falls back to text only
}

// One chip per hazard kind. hazardFromName() in hd2_model.h has already turned
// the API's free-text hazard name into one of these; kHazardOther is the
// catch-all that keeps an unrecognised hazard visible rather than dropped.
IconRef hazardIcon(HazardKind k) {
  switch (k) {
    case kHazardFire:   return {icons::hazFire, icons::hazFireW, icons::hazFireH};
    case kHazardIon:    return {icons::hazIon, icons::hazIonW, icons::hazIonH};
    case kHazardCold:   return {icons::hazCold, icons::hazColdW, icons::hazColdH};
    case kHazardMeteor: return {icons::hazMeteor, icons::hazMeteorW, icons::hazMeteorH};
    case kHazardStorm:  return {icons::hazStorm, icons::hazStormW, icons::hazStormH};
    case kHazardTremor: return {icons::hazTremor, icons::hazTremorW, icons::hazTremorH};
    default:            return {icons::hazOther, icons::hazOtherW, icons::hazOtherH};
  }
}

// Source coordinate, in 24.8 fixed point, for destination pixel `d` when
// scaling `dstLen` pixels down onto `srcLen`. Half-pixel centred, so the
// interpolation is symmetric, and clamped at the left/top edge where the
// centring would otherwise read off the start of the array.
inline int32_t srcCoord(int32_t d, int32_t srcLen, int32_t dstLen) {
  const int32_t f = ((2 * d + 1) * srcLen * 256) / (2 * dstLen) - 128;
  return f < 0 ? 0 : f;
}

// Blend two RGB565 pixels, `t` running 0..255 from `a` to `b`. The channels are
// interpolated in their packed 5/6/5 precision, which is all the panel can show
// anyway.
inline uint16_t lerp565(uint16_t a, uint16_t b, int t) {
  const int ar = a >> 11, ag = (a >> 5) & 0x3F, ab = a & 0x1F;
  const int br = b >> 11, bg = (b >> 5) & 0x3F, bb = b & 0x1F;
  return (uint16_t)(((ar + (((br - ar) * t) >> 8)) << 11) |
                    ((ag + (((bg - ag) * t) >> 8)) << 5) |
                     (ab + (((bb - ab) * t) >> 8)));
}

}  // namespace

// ---------------------------------------------------------------------------
//  Small helpers
// ---------------------------------------------------------------------------

static String upper(const String &s) {
  String t = s;
  t.toUpperCase();
  return t;
}

// Humans holding a planet is good news; anyone else gets the red treatment.
static uint16_t factionColor(const String &faction) {
  return faction.equalsIgnoreCase("Humans") ? theme::green : theme::red;
}

// What to *call* a faction on screen. The API names our side "Humans"; the
// game calls them the SEAF, and that is what the card should say. Purely a
// relabelling at the point of drawing — every match above and in hd2_api.cpp
// still runs against the API's own spelling, which this never rewrites.
static String factionDisplayName(const String &faction) {
  String f = faction;
  f.toLowerCase();
  return f.startsWith("human") ? String(F("SEAF")) : faction;
}

// The card's accent, taken from whoever is attacking. Everything tinted by it
// — the alert ribbon, the scene weave, the invader's half of the tug-of-war —
// is describing that faction, so they all move together.
static uint16_t factionAccent(const String &faction) {
  String f = faction;
  f.toLowerCase();
  if (f.startsWith("illuminate")) return theme::purple;
  if (f.startsWith("terminid")) return theme::amber;
  if (f.startsWith("automaton")) return theme::red;
  if (f.startsWith("human")) return theme::blue;
  return theme::gold;
}

// Anchor point inside a w*h box for a given TFT_eSPI datum.
static void datumAnchor(uint8_t datum, int16_t w, int16_t h, int16_t &ax, int16_t &ay) {
  switch (datum) {
    case TC_DATUM: ax = w / 2; ay = 0;     break;
    case TR_DATUM: ax = w;     ay = 0;     break;
    case ML_DATUM: ax = 0;     ay = h / 2; break;
    case MC_DATUM: ax = w / 2; ay = h / 2; break;
    case MR_DATUM: ax = w;     ay = h / 2; break;
    default:       ax = 0;     ay = 0;     break;  // TL_DATUM
  }
}

// "Omega" -> "OMEGA SECTOR". The API gives the bare name; the card wants the
// full form the game uses.
static String sectorLabel(const String &sector) {
  if (!sector.length()) return String();
  String s = upper(sector);
  if (!s.endsWith(" SECTOR")) s += F(" SECTOR");
  return s;
}

// Player counts, grouped: 13637 -> "13,637".
//
// This used to zero-pad to six digits ("013,637") so the footer's left block
// kept a constant width and did not twitch as divers came and went. The
// padding read as part of the number rather than as alignment, so it is gone;
// the callers hold their own width instead — see kCountBoxW below and the
// fixed-width column boxes in drawCampaignBody().
// Width to clear for a formatCount() field, in FONT_BODY. Six grouped digits
// ("999,999") is past any plausible diver count, so the box never has to grow
// mid-frame and the number never has to be padded to fill it.
static constexpr int16_t kCountBoxW = 62;

static String formatCount(uint32_t v) {
  char digits[16];
  snprintf(digits, sizeof(digits), "%lu", (unsigned long)v);
  const int n = (int)strlen(digits);
  String out;
  out.reserve(n + n / 3);
  for (int i = 0; i < n; i++) {
    if (i && (n - i) % 3 == 0) out += ',';
    out += digits[i];
  }
  return out;
}

// A measured rate of change, e.g. "+04.426% / h". Zero-padded to a fixed width
// for the same reason as the player count.
static String formatRate(float pctPerHour) {
  float a = fabsf(pctPerHour);
  if (a > 99.999f) a = 99.999f;  // clamp rather than let the field jump width
  char buf[24];
  snprintf(buf, sizeof(buf), "%c%.1f%% / h", pctPerHour < 0.0f ? '-' : '+', a);
  return String(buf);
}

// The target currently on screen, or nullptr when the order has no tasks.
static const OrderTask *activeTask(const HudModel &m, uint8_t idx) {
  if (!m.order.valid || m.order.taskCount <= 0) return nullptr;
  if (idx >= (uint8_t)m.order.taskCount) idx = 0;
  return &m.order.tasks[idx];
}

// --- Rates ------------------------------------------------------------------
//
// Everything the card says about *change* is measured here, by diffing the
// current poll against the sample the poll loop kept from the previous one.
// The API has no rate field; without two samples there is no number, and the
// card is expected to say so rather than print a zero.
struct CardRates {
  bool have = false;   // is there a usable pair of samples at all
  float pct = 0.0f;    // percentage points per hour on the leading bar
};

static CardRates cardRates(const HudModel &m, uint8_t idx, const OrderTask &t) {
  CardRates r;
  if (idx >= (uint8_t)kMaxOrderTasks) return r;
  const PlanetInfo &p = t.planet;
  const RateSample &h = m.history[idx];
  if (!p.valid || !h.valid || h.planetIndex != p.index) return r;

  if (p.event.active) {
    // Only against the same defence. When one event ends and another begins the
    // health pair restarts, and diffing across that would report a swing that
    // never happened.
    if (!h.haveEvent || h.eventEnd != p.event.endTime) return r;
    r.have = ratePerHour(p.event.defended(), p.observedAt, h.eventPct, h.at, r.pct);
  } else if (taskIsLiberation(t.taskType)) {
    r.have = ratePerHour(p.liberation, p.observedAt, h.libPct, h.at, r.pct);
  }
  return r;
}

// Everything that, when it changes, warrants a full body repaint. The clocks,
// WiFi dot and footer are deliberately excluded — they update themselves
// through their own small sprites, and so is the card, which has its own
// signature below because the carousel repaints it on a 7-second beat.
static String contentSignature(const HudModel &m) {
  if (!m.haveData) return F("boot");
  String s;
  s.reserve(96);
  if (m.order.valid) {
    s = F("mo|");
    s += String(m.order.id);
    s += '|';
    s += String(m.order.taskCount);
    return s;
  }
  // The campaign screen moves with liberation, so its figures join the
  // signature — otherwise a planet at 41.2% would sit there reading 40.8%
  // until the war totals happened to change.
  s = F("idle|");
  if (m.campaign.valid) {
    s += F("camp|");
    s += String(m.campaign.index);
    s += '|';
    s += String(m.campaign.liberation, 3);
    s += '|';
    s += String(m.campaign.playerCount);
    s += '|';
  }
  s += String(m.war.playerCount);
  s += '|';
  s += String(m.war.missionSuccessRate);
  s += '|';
  s += formatCompact(m.war.totalKills);
  return s;
}

// Everything the card draws, including which target it is. The two observation
// timestamps stand in for the derived rates: they are what those are computed
// from, and they move exactly when the rates do.
static String targetSignature(const HudModel &m, uint8_t idx) {
  const OrderTask *t = activeTask(m, idx);
  if (!t) return F("none");
  const PlanetInfo &p = t->planet;
  String s;
  s.reserve(160);
  s = String(idx);
  s += '/';
  s += String(m.order.taskCount);
  s += '|';
  s += m.order.title;
  s += '|';
  s += String(m.order.rewardAmount);
  s += '|';
  s += String(t->taskType);
  s += '|';
  s += String(t->planetIndex);
  s += '|';
  s += t->complete ? '1' : '0';
  s += '|';
  s += p.name;
  s += '|';
  s += p.sector;
  s += '|';
  s += p.biome;
  s += '|';
  s += p.owner;
  s += '|';
  s += String(p.playerCount);
  s += '|';
  s += String((int)(p.liberation * 100.0f));
  s += '|';
  s += String((unsigned long)p.observedAt);
  s += '|';
  s += String((unsigned long)m.history[idx < kMaxOrderTasks ? idx : 0].at);
  s += '|';
  for (uint8_t i = 0; i < p.hazardCount; i++) s += (char)('0' + (int)p.hazards[i]);
  s += '|';
  if (p.event.active) {
    s += p.event.faction;
    s += '@';
    s += String((unsigned long)p.event.endTime);
    s += '@';
    s += String((int)(p.event.defended() * 100.0f));
  }
  return s;
}

// How long each target of a multi-target order stays on screen. Long enough to
// read the card and glance away; short enough that a three-target order comes
// round inside a normal look at the desk.
static const uint32_t kTargetCycleMs = 7000;

// The status line for an objective that cannot honestly be shown as a
// percentage: defend tasks with nothing attacking them, and any type we don't
// recognise.
struct StatusLine {
  String text;
  uint16_t color;
};

static StatusLine objectiveStatus(const OrderTask &t) {
  if (t.taskType == kTaskTypeDefend) {
    // Defence is pass/fail per task, and the API says which it is. The planet's
    // health only tells us whether an assault is in progress right now.
    if (t.complete) return {String(F("HELD")), theme::green};
    if (!t.planet.valid) return {String(F("AT RISK")), theme::gold};
    return t.planet.owner.equalsIgnoreCase("Humans")
               ? StatusLine{String(F("STANDING BY")), theme::gold}
               : StatusLine{String(F("LOST")), theme::red};
  }
  // Unknown objective kind: report the one thing the API is unambiguous about
  // rather than inventing a metric for it.
  return t.complete ? StatusLine{String(F("OBJECTIVE COMPLETE")), theme::green}
                    : StatusLine{String(F("IN PROGRESS")), theme::gold};
}

// Geometry of the three icon tiles the no-order screen uses, and of the two-up
// boxes on the WiFi setup screen.
static constexpr int16_t kTileW = (contentW - 2 * tileGap) / 3;  // 142
static constexpr int16_t kStatW = (contentW - statGap) / 2;      // 216
static constexpr int16_t kStatInsetX = 12;
static constexpr int16_t kStatValueDy = 21;
static constexpr int16_t kStatValueH = 20;

// The two progress tracks, and where a lone track sits when there is only one.
static constexpr int16_t kBar2Y = barsY + cardBarH + barsGap;
static constexpr int16_t kSoloBarY = barsY + (cardBarH + barsGap) / 2;
static constexpr int16_t kRateX = cardX + trackW + rateGap;

// ---------------------------------------------------------------------------
//  Lifecycle
// ---------------------------------------------------------------------------

void HUDRenderer::begin() {
  _tft.init();
  // Rotation 1 turns the native 320x480 portrait panel into 480x320 landscape.
  // If the image is upside down for how the board sits on your desk, use 3.
  _tft.setRotation(1);
  _tft.fillScreen(theme::bg);

  // TFT_BL is driven by TFT_eSPI when TFT_BL is defined, but do it explicitly
  // so the backlight is on even if that define is later removed.
#ifdef TFT_BL
  pinMode(TFT_BL, OUTPUT);
  digitalWrite(TFT_BL, TFT_BACKLIGHT_ON);
#endif

  _targetSwitchMs = millis();
  invalidate();
}

void HUDRenderer::invalidate() {
  _chromeDrawn = false;
  _contentSig = "";
  _targetSig = "";
  _clockSig = "";
  _footerSig = "";
  _wifiSig = -1;
}

// ---------------------------------------------------------------------------
//  Primitives
// ---------------------------------------------------------------------------

void HUDRenderer::textBox(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t bg,
                          const GFXfont *font, uint16_t fg, uint8_t datum,
                          const String &s, int16_t inset) {
  TFT_eSprite spr(&_tft);
  spr.setColorDepth(16);
  if (spr.createSprite(w, h)) {
    spr.fillSprite(bg);
    spr.setFreeFont(font);
    spr.setTextColor(fg, bg);
    spr.setTextDatum(datum);
    int16_t ax, ay;
    datumAnchor(datum, w, h, ax, ay);
    if (datum == TL_DATUM || datum == ML_DATUM) ax += inset;
    if (datum == TR_DATUM || datum == MR_DATUM) ax -= inset;
    spr.drawString(s.c_str(), ax, ay);
    spr.pushSprite(x, y);
    spr.deleteSprite();
    return;
  }
  // Sprite allocation failed (heap pressure) — fall back to direct drawing.
  // Slight flicker, but never a blank region.
  _tft.fillRect(x, y, w, h, bg);
  _tft.setFreeFont(font);
  _tft.setTextColor(fg, bg);
  _tft.setTextDatum(datum);
  int16_t ax, ay;
  datumAnchor(datum, w, h, ax, ay);
  if (datum == TL_DATUM || datum == ML_DATUM) ax += inset;
  if (datum == TR_DATUM || datum == MR_DATUM) ax -= inset;
  _tft.drawString(s.c_str(), x + ax, y + ay);
}

void HUDRenderer::drawHatch(int16_t x, int16_t y, int16_t w, int16_t h, int16_t pitch,
                            uint16_t c) {
  if (pitch < 3 || w <= 0 || h <= 0) return;
  // 45-degree stripes, two pixels thick. Stepping the start column one to the
  // right per row is the whole of the diagonal, and it clips to the box for
  // free — which drawLine() would not.
  for (int16_t j = 0; j < h; j++) {
    for (int16_t i = (pitch - (j % pitch)) % pitch; i < w; i += pitch) {
      _tft.drawFastHLine(x + i, y + j, min<int16_t>(2, w - i), c);
    }
  }
}

// The Earth/gold-sweep wash, bilinearly scaled onto an arbitrary destination
// rect. Restored from 46d2315, where it backed the old Major Order title bar;
// generalised here to take the whole destination rect (dx/dy/dw/dh) rather
// than assuming the header bar's geometry, so the objective bar can wear it.
//
// (sx, sy, sw, sh) is the sub-rect of that destination being repainted, which
// lets callers touch up a slice (the clock flag, say) without redrawing the
// whole bar and still sample the right part of the wash.
void HUDRenderer::drawWash(int16_t sx, int16_t sy, int16_t sw, int16_t sh,
                           int16_t dx, int16_t dy, int16_t dw, int16_t dh) {
  using namespace headerart;
  if (sw <= 0 || sh <= 0) return;

  // pushImage() streams the buffer straight at the panel, which wants each
  // pixel MSB first; the words below are native-endian.
  const bool swap = _tft.getSwapBytes();
  _tft.setSwapBytes(true);

  uint16_t line[cardW];
  for (int16_t j = 0; j < sh; ++j) {
    const int32_t fy = srcCoord(sy - dy + j, headerBgH, dh);
    const int32_t y0 = fy >> 8;
    const int32_t y1 = (y0 + 1 < headerBgH) ? y0 + 1 : y0;
    const int ty = fy & 0xFF;
    const uint16_t *r0 = &headerBg[y0 * headerBgW];
    const uint16_t *r1 = &headerBg[y1 * headerBgW];

    for (int16_t i = 0; i < sw; ++i) {
      const int32_t fx = srcCoord(sx - dx + i, headerBgW, dw);
      const int32_t x0 = fx >> 8;
      const int32_t x1 = (x0 + 1 < headerBgW) ? x0 + 1 : x0;
      const int tx = fx & 0xFF;
      line[i] = lerp565(lerp565(pgm_read_word(&r0[x0]), pgm_read_word(&r0[x1]), tx),
                        lerp565(pgm_read_word(&r1[x0]), pgm_read_word(&r1[x1]), tx),
                        ty);
    }
    _tft.pushImage(sx, sy + j, sw, 1, line);
  }

  _tft.setSwapBytes(swap);
}

// A biome plate, scaled up into `dw x dh`. Same bilinear walk as drawWash(),
// but reading a caller-supplied source rather than the Earth wash: the plates
// are stored at half size (see tools/gen_biomes.py) precisely because this
// scaler already exists, so the set fits in flash without new code.
void HUDRenderer::drawBiome(const uint16_t *src, int16_t sw, int16_t sh, int16_t dx,
                            int16_t dy, int16_t dw, int16_t dh) {
  if (!src || dw <= 0 || dh <= 0) return;

  const bool swap = _tft.getSwapBytes();
  _tft.setSwapBytes(true);

  uint16_t line[cardW];
  const int16_t span = dw > cardW ? cardW : dw;
  for (int16_t j = 0; j < dh; ++j) {
    const int32_t fy = srcCoord(j, sh, dh);
    const int32_t y0 = fy >> 8;
    const int32_t y1 = (y0 + 1 < sh) ? y0 + 1 : y0;
    const int ty = fy & 0xFF;
    const uint16_t *r0 = &src[y0 * sw];
    const uint16_t *r1 = &src[y1 * sw];

    for (int16_t i = 0; i < span; ++i) {
      const int32_t fx = srcCoord(i, sw, dw);
      const int32_t x0 = fx >> 8;
      const int32_t x1 = (x0 + 1 < sw) ? x0 + 1 : x0;
      const int tx = fx & 0xFF;
      line[i] = lerp565(lerp565(pgm_read_word(&r0[x0]), pgm_read_word(&r0[x1]), tx),
                        lerp565(pgm_read_word(&r1[x0]), pgm_read_word(&r1[x1]), tx),
                        ty);
    }
    _tft.pushImage(dx, dy + j, span, 1, line);
  }

  _tft.setSwapBytes(swap);
}

// The objective bar's own slice of the wash, in whole or in part.
void HUDRenderer::drawObjWash(int16_t sx, int16_t sy, int16_t sw, int16_t sh) {
  drawWash(sx, sy, sw, sh, cardX, objY, cardW, objH);
}

// Text over the objective bar's wash. textBox() fills its sprite with a flat
// colour, which would punch a hole in the artwork, so this paints the wash
// into the destination first and then draws the glyphs straight onto it with a
// transparent background.
void HUDRenderer::washText(int16_t x, int16_t y, int16_t w, int16_t h,
                           const GFXfont *font, uint16_t fg, uint8_t datum,
                           const String &s) {
  if (w <= 0 || h <= 0) return;
  drawObjWash(x, y, w, h);
  _tft.setFreeFont(font);
  _tft.setTextColor(fg);  // no bg colour == glyphs only, wash shows through
  _tft.setTextDatum(datum);
  int16_t ax, ay;
  datumAnchor(datum, w, h, ax, ay);
  _tft.drawString(s.c_str(), x + ax, y + ay);
}

void HUDRenderer::drawRule(int16_t y) {
  _tft.drawFastHLine(padX, y, contentW, theme::goldDim);
}

int16_t HUDRenderer::tileX(int i) {
  return padX + i * (kTileW + tileGap);
}

void HUDRenderer::drawTile(int i, const uint8_t *icon, int16_t iw, int16_t ih,
                           const String &value, uint16_t valueColor) {
  const int16_t x = tileX(i);
  _tft.fillRect(x, tileY, kTileW, tileH, theme::panel);
  _tft.drawRect(x, tileY, kTileW, tileH, theme::goldDim);
  // The icon stands in for what used to be an ALL-CAPS label, so it is drawn
  // at label weight rather than value weight.
  _tft.drawBitmap(x + tileInsetX, tileY + tileIconDy, icon, iw, ih, theme::goldDim);

  // Drop a size rather than run off the edge of the tile.
  _tft.setFreeFont(FONT_VALUE);
  const GFXfont *font = (_tft.textWidth(value.c_str()) > kTileW - 2 * tileInsetX)
                            ? FONT_LABEL
                            : FONT_VALUE;
  textBox(x + 1, tileY + tileValueDy, kTileW - 2, tileValueH, theme::panel, font,
          valueColor, ML_DATUM, value, tileInsetX - 1);
}

void HUDRenderer::drawStatBox(int16_t x, int16_t y, int16_t w, int16_t h,
                              const String &label, const String &value,
                              uint16_t valueColor) {
  _tft.fillRect(x, y, w, h, theme::panel);
  _tft.drawRect(x, y, w, h, theme::goldDim);
  textBox(x + 1, y + 5, w - 2, 15, theme::panel, FONT_LABEL, theme::grey, ML_DATUM,
          label, kStatInsetX - 1);

  // Drop a size rather than run off the edge of the box (long values show up
  // in the WiFi-setup screen, and for very large player counts).
  _tft.setFreeFont(FONT_VALUE);
  const GFXfont *valueFont =
      (_tft.textWidth(value.c_str()) > w - 2 * kStatInsetX) ? FONT_LABEL : FONT_VALUE;
  textBox(x + 1, y + kStatValueDy, w - 2, kStatValueH, theme::panel, valueFont,
          valueColor, ML_DATUM, value, kStatInsetX - 1);
}

int16_t HUDRenderer::badgeWidth(const String &faction) {
  const String label = upper(faction.length() ? factionDisplayName(faction)
                                              : String("UNKNOWN"));
  const ColorIconRef ic = factionIcon(faction);

  _tft.setFreeFont(FONT_LABEL);
  int16_t w = _tft.textWidth(label.c_str()) + 2 * badgePadX;
  if (ic.px) w += ic.w + badgeIconGap;
  return w > badgeMaxW ? badgeMaxW : w;
}

void HUDRenderer::drawBadge(const String &faction, int16_t x, int16_t y, int16_t h) {
  const String label = upper(faction.length() ? factionDisplayName(faction)
                                              : String("UNKNOWN"));
  const uint16_t c = factionColor(faction);
  const ColorIconRef ic = factionIcon(faction);
  const int16_t w = badgeWidth(faction);

  _tft.fillRect(x, y, w, h, theme::bg);
  _tft.drawRect(x, y, w, h, c);

  if (ic.px) {
    // Icon then label, left-aligned as a pair. Since the badge is sized to
    // fit exactly, that reads as centred. textBox() clears the icon slot on
    // its way past, so the bitmap goes down afterwards.
    textBox(x + 1, y + 1, w - 2, h - 2, theme::bg, FONT_LABEL, c, ML_DATUM, label,
            badgePadX + ic.w + badgeIconGap - 1);
    // The icon arrays are plain uint16_t, so on a little-endian ESP32 they
    // reach the panel byte-reversed unless this is set -- which turns the
    // Automaton's salmon into a pale blue. headerBg never hit this because it
    // goes out through drawPixel(), a pixel at a time.
    _tft.setSwapBytes(true);
    _tft.pushImage(x + badgePadX, y + (h - ic.h) / 2, ic.w, ic.h, ic.px,
                   facicons::kTransparent);
    _tft.setSwapBytes(false);
  } else {
    textBox(x + 1, y + 1, w - 2, h - 2, theme::bg, FONT_LABEL, c, MC_DATUM, label);
  }
}

void HUDRenderer::drawRateBar(int16_t y, float pct, uint16_t fill, bool haveRate,
                              float rate) {
  const float clamped = pct < 0.0f ? 0.0f : (pct > 100.0f ? 100.0f : pct);
  const int16_t fillW = (int16_t)((trackW - 2) * (clamped / 100.0f) + 0.5f);

  _tft.fillRect(cardX, y, trackW, cardBarH, theme::track);
  if (fillW > 0) _tft.fillRect(cardX + 1, y + 1, fillW, cardBarH - 2, fill);
  _tft.drawRect(cardX, y, trackW, cardBarH, theme::cardEdge);

  // Chevron cap riding the leading edge of the fill, once there is room for it
  // to sit inside the fill rather than straddle the track.
  if (fillW > icons::trendW + 6) {
    _tft.drawBitmap(cardX + 1 + fillW - icons::trendW - 3,
                    y + (cardBarH - icons::trendH) / 2, icons::trend, icons::trendW,
                    icons::trendH, theme::text);
  }

  // Measured %-per-hour, in a fixed column so the two bars' readouts line up.
  _tft.drawBitmap(kRateX, y + (cardBarH - icons::trendH) / 2, icons::trend,
                  icons::trendW, icons::trendH, haveRate ? fill : theme::goldMute);
  const int16_t tx = kRateX + icons::trendW + rateIconGap;
  textBox(tx, y, cardX + cardW - tx, cardBarH, theme::bg, FONT_BODY,
          haveRate ? theme::text : theme::grey, ML_DATUM,
          haveRate ? formatRate(rate) : String(F("--")));
}

void HUDRenderer::drawIdleBar(int16_t y, const String &label, uint16_t color) {
  _tft.fillRect(cardX, y, trackW, cardBarH, theme::track);
  _tft.drawRect(cardX, y, trackW, cardBarH, theme::cardEdge);
  textBox(cardX + 1, y + 1, trackW - 2, cardBarH - 2, theme::track, FONT_LABEL, color,
          MC_DATUM, label);
  _tft.fillRect(kRateX, y, cardX + cardW - kRateX, cardBarH, theme::bg);
}

// ---------------------------------------------------------------------------
//  Chrome — outer frame, corner brackets, header row
// ---------------------------------------------------------------------------

void HUDRenderer::drawFrame() {
  const int16_t x0 = frameX, y0 = frameY;
  const int16_t x1 = frameX + frameW - 1, y1 = frameY + frameH - 1;

  _tft.drawRect(x0, y0, frameW, frameH, theme::goldDim);

  // Squared-off corner accents: two arms per corner, brighter and thicker
  // than the frame itself.
  const int16_t L = bracketLen, T = bracketThick;
  // top-left
  _tft.fillRect(x0, y0, L, T, theme::gold);
  _tft.fillRect(x0, y0, T, L, theme::gold);
  // top-right
  _tft.fillRect(x1 - L + 1, y0, L, T, theme::gold);
  _tft.fillRect(x1 - T + 1, y0, T, L, theme::gold);
  // bottom-left
  _tft.fillRect(x0, y1 - T + 1, L, T, theme::gold);
  _tft.fillRect(x0, y1 - L + 1, T, L, theme::gold);
  // bottom-right
  _tft.fillRect(x1 - L + 1, y1 - T + 1, L, T, theme::gold);
  _tft.fillRect(x1 - T + 1, y1 - L + 1, T, L, theme::gold);
}

void HUDRenderer::drawStatusHeader(const String &title) {
  // Text only, flush with the content column. The emblem is drawn on this
  // screen at centrepiece size instead; at header height it read as a blob.
  textBox(padX, headerY, 200, headerH, theme::bg, FONT_LABEL, theme::gold, ML_DATUM,
          title.length() ? title : String(F("SUPER EARTH")));
  drawRule(rule1Y);
}

void HUDRenderer::drawWifi(bool up) {
  const int8_t sig = up ? 1 : 0;
  if (sig == _wifiSig) return;
  _wifiSig = sig;

  const uint16_t c = up ? theme::green : theme::red;

  if (_cardMode) {
    // The card's footer is already narrating the link state in words ("SYNCED"
    // vs "STALE"), so here the dot alone carries it.
    const int16_t cx = contentR - footDotR;
    const int16_t cy = cardFootY + cardFootH / 2;
    _tft.fillRect(cx - footDotR, cy - footDotR, 2 * footDotR + 1, 2 * footDotR + 1,
                  theme::bg);
    _tft.fillCircle(cx, cy, footDotR, c);
    return;
  }

  const int16_t dotR = 5;
  const int16_t dotCx = contentR - dotR;
  const int16_t cy = headerY + headerH / 2;
  const char *label = up ? "WIFI" : "OFFLINE";

  // Label right-aligned just left of the dot.
  textBox(contentR - 110, headerY, 110 - (2 * dotR + 6), headerH, theme::bg,
          FONT_LABEL, c, MR_DATUM, String(label));

  _tft.fillRect(dotCx - dotR, cy - dotR, 2 * dotR + 1, 2 * dotR + 1, theme::bg);
  _tft.fillCircle(dotCx, cy, dotR, c);
}

// ---------------------------------------------------------------------------
//  The Major Order card
// ---------------------------------------------------------------------------

void HUDRenderer::drawObjectiveBar(const HudModel &m, const OrderTask &t,
                                   uint16_t accent) {
  // The Earth wash carries the bar; the border still reads over it.
  drawObjWash(cardX, objY, cardW, objH);
  _tft.drawRect(cardX, objY, cardW, objH, theme::cardEdge);

  const bool defending = (t.taskType == kTaskTypeDefend) || t.planet.event.active;
  const bool liberating = taskIsLiberation(t.taskType);

  IconRef ic{icons::target, icons::targetW, icons::targetH};
  String word = F("OBJECTIVE");
  if (defending) {
    ic = {icons::shield, icons::shieldW, icons::shieldH};
    word = F("DEFENSE");
  } else if (liberating) {
    ic = {icons::liberate, icons::liberateW, icons::liberateH};
    word = F("LIBERATION");
  }

  // --- gold flag: the order's own expiry, at the far right -----------------
  // Sized against the widest string formatDuration() can produce so it never
  // resizes under the ticking clock.
  _tft.setFreeFont(FONT_LABEL);
  int16_t clockW = _tft.textWidth("88d 88h");
  clockW = max(clockW, _tft.textWidth("EXPIRED"));
  const int16_t flagW = flagCut + 2 * flagPad + clockW;
  const int16_t flagX = cardX + cardW - flagW;
  const int16_t flagY = objY + 1, flagH = objH - 2;

  // Leading edge cut back on the diagonal, the way the game's own ribbons are.
  _tft.fillTriangle(flagX, flagY + flagH - 1, flagX + flagCut, flagY,
                    flagX + flagCut, flagY + flagH - 1, theme::gold);
  _flagX = flagX + flagCut;
  _flagW = cardX + cardW - _flagX;

  // --- status word, then the carousel pips ---------------------------------
  // Drawn before the right-hand clock so its extent is known: the bar packs
  // from both ends, and "VICTORY IN:" has to know where the left block stops.
  const int16_t iconX = cardX + objPad;
  const int16_t wordX = iconX + ic.w + objIconGap;
  _tft.setFreeFont(FONT_LABEL);
  const int16_t wordW = _tft.textWidth(word.c_str());
  washText(wordX, objY + 1, wordW, objH - 2, FONT_LABEL, theme::text, ML_DATUM,
           word);
  _tft.drawBitmap(iconX, objY + (objH - ic.h) / 2, ic.bits, ic.w, ic.h, accent);

  int16_t leftEnd = wordX + wordW;

  const int count = m.order.taskCount;
  if (count > 1) {
    const int16_t pipS = 6, pipGap = 5;
    int16_t px = wordX + wordW + objPipGap;
    const int16_t py = objY + (objH - pipS) / 2;
    for (int i = 0; i < count; i++, px += pipS + pipGap) {
      if (i == _targetIdx) {
        _tft.fillRect(px, py, pipS, pipS, theme::gold);
      } else {
        _tft.drawRect(px, py, pipS, pipS, theme::goldDim);
      }
    }
    leftEnd = px - pipGap;
  }

  // --- "VICTORY IN:" — the defence's own deadline, not the order's ---------
  // The clock itself always fits; only its label is optional. When the status
  // word and pips leave no room the label is dropped rather than overprinted,
  // which is what "DEFENSE" + "VICTORY IN:" used to do on a three-target
  // invasion.
  _victoryX = 0;
  _victoryW = 0;
  if (t.planet.event.active) {
    _tft.setFreeFont(FONT_LABEL);
    const int16_t vW = max(_tft.textWidth("88d 88h"), _tft.textWidth("EXPIRED")) + 2;
    _tft.setFreeFont(FONT_BODY);
    const String label = F("VICTORY IN:");
    const int16_t labelW = _tft.textWidth(label.c_str());

    _victoryX = flagX - victoryGap - vW;
    _victoryW = vW;

    const int16_t labelX = _victoryX - 6 - labelW;
    if (labelX > leftEnd + objIconGap) {
      washText(labelX, objY + 1, labelW, objH - 2, FONT_BODY, theme::grey,
               MR_DATUM, label);
    }
  }
}

void HUDRenderer::drawIdentity(const OrderTask &t, uint16_t accent) {
  _tft.fillRect(cardX, idyY, cardW, idyH, theme::bg);
  _tft.drawRect(cardX, idyY, cardW, idyH, theme::cardEdge);

  const PlanetInfo &p = t.planet;
  const int16_t iconX = cardX + idyPad;
  const int16_t nameX = iconX + icons::globeW + idyIconGap;
  _tft.drawBitmap(iconX, idyY + (idyH - icons::globeH) / 2, icons::globe,
                  icons::globeW, icons::globeH, accent);

  if (!p.valid) {
    textBox(nameX, idyY + idyNameY, cardX + cardW - idyPad - nameX, idyNameH,
            theme::bg, FONT_VALUE, theme::grey, ML_DATUM,
            t.planetIndex >= 0 ? F("PLANET DATA UNAVAILABLE")
                               : F("GALAXY-WIDE OBJECTIVE"));
    return;
  }

  // Who holds the planet, right-aligned; the name gets whatever is left.
  const int16_t bw = badgeWidth(p.owner);
  const int16_t badgeX = cardX + cardW - idyPad - bw;
  drawBadge(p.owner, badgeX, idyY + (idyH - badgeH) / 2, badgeH);

  const int16_t availW = badgeX - badgeGap - nameX;
  const String name = upper(p.name);

  // Anton is condensed, but planet names run to "ANGEL'S VENTURE"; drop a cut
  // and then trim rather than run under the badge.
  const GFXfont *nameFont = FONT_HEADLINE;
  _tft.setFreeFont(nameFont);
  if (_tft.textWidth(name.c_str()) > availW) {
    nameFont = FONT_HEADLINE_SM;
    _tft.setFreeFont(nameFont);
  }
  String shown = name;
  while (shown.length() > 1 && _tft.textWidth(shown.c_str()) > availW) {
    shown.remove(shown.length() - 1);
  }
  textBox(nameX, idyY + idyNameY, availW, idyNameH, theme::bg, nameFont, theme::text,
          ML_DATUM, shown);

  const String sector = sectorLabel(p.sector);
  if (sector.length()) {
    textBox(nameX, idyY + idySectorY, availW, idySectorH, theme::bg, FONT_BODY,
            theme::grey, ML_DATUM, sector);
  }
}

void HUDRenderer::drawAlertRibbon(const OrderTask &t, uint16_t accent) {
  const bool alert = t.planet.event.active;
  const uint16_t fill = alert ? theme::alarm : theme::panel;
  const uint16_t edge = alert ? lerp565(theme::bg, accent, 150) : theme::cardEdge;
  const uint16_t stripe = alert ? lerp565(fill, accent, 110) : theme::goldDim;

  _tft.fillRect(cardX, ribY, cardW, ribH, fill);
  drawHatch(cardX + 1, ribY + 1, ribStripeW, ribH - 2, ribStripePitch, stripe);
  drawHatch(cardX + cardW - 1 - ribStripeW, ribY + 1, ribStripeW, ribH - 2,
            ribStripePitch, stripe);
  _tft.drawRect(cardX, ribY, cardW, ribH, edge);

  const int16_t innerX = cardX + 1 + ribStripeW;
  const int16_t innerW = cardW - 2 - 2 * ribStripeW;

  if (!alert) {
    // No hostile event on this planet, so there is no invasion to call out.
    // The objective's own status is the honest thing to put here.
    const StatusLine st = objectiveStatus(t);
    textBox(innerX, ribY + 1, innerW, ribH - 2, fill, FONT_LABEL, st.color, MC_DATUM,
            st.text);
    return;
  }

  const ColorIconRef ic = factionIcon(t.planet.event.faction);
  const String text =
      upper(factionDisplayName(t.planet.event.faction)) + F(" INVASION DETECTED");
  _tft.setFreeFont(FONT_LABEL);
  const int16_t textW = _tft.textWidth(text.c_str());
  const int16_t blockW = textW + (ic.px ? ic.w + ribIconGap : 0);
  const int16_t blockX = innerX + (innerW - blockW) / 2;

  textBox(innerX, ribY + 1, innerW, ribH - 2, fill, FONT_LABEL, accent, ML_DATUM, text,
          blockX - innerX + (ic.px ? ic.w + ribIconGap : 0));
  if (ic.px) {
    _tft.setSwapBytes(true);
    _tft.pushImage(blockX, ribY + (ribH - ic.h) / 2, ic.w, ic.h, ic.px,
                   facicons::kTransparent);
    _tft.setSwapBytes(false);
  }
}

void HUDRenderer::drawScene(const HudModel &m, const OrderTask &t, uint16_t accent) {
  // There is no per-planet artwork in the public API and none is going to be
  // invented here, so the biome band is a woven panel tinted by whoever is
  // attacking rather than a photograph of somewhere.
  const uint16_t base = lerp565(theme::panel, accent, 26);
  const uint16_t weave = lerp565(base, accent, 30);

  _tft.fillRect(cardX, sceneY, cardW, sceneH, base);
  for (int16_t j = sceneWeavePitch - 1; j < sceneH - 1; j += sceneWeavePitch) {
    _tft.drawFastHLine(cardX + 1, sceneY + j, cardW - 2, weave);
  }
  _tft.drawRect(cardX, sceneY, cardW, sceneH, theme::cardEdge);

  // The device's own mark, on the right. Everything to its left is data.
  const int16_t crestX = cardX + cardW - scenePad - icons::crestW;
  _tft.drawBitmap(crestX, sceneY + (sceneH - icons::crestH) / 2, icons::crest,
                  icons::crestW, icons::crestH, theme::goldDim);

  const int16_t textX = cardX + scenePad;
  const int16_t textW = crestX - scenePad - textX;

  // The order's title, which the card has no other room for.
  String title = upper(t.valid ? String() : String());  // placeholder, set below
  (void)title;

  const PlanetInfo &p = t.planet;
  if (p.biome.length()) {
    textBox(textX, sceneY + sceneBiomeDy, textW, sceneBiomeH, base, FONT_BODY,
            theme::grey, ML_DATUM, upper(p.biome));
  }

  // One chip per hazard the API actually reported for this planet — no more.
  // A planet with none reports the sentinel "None", which hd2_model.h drops, so
  // an empty row here means an empty hazard list, not missing data.
  int16_t cx = textX;
  for (uint8_t i = 0; i < p.hazardCount; i++) {
    const IconRef ic = hazardIcon(p.hazards[i]);
    if (cx + ic.w > textX + textW) break;
    _tft.drawBitmap(cx, sceneY + sceneChipDy, ic.bits, ic.w, ic.h, accent);
    cx += ic.w + chipGap;
  }
}

void HUDRenderer::drawProgress(const HudModel &m, const OrderTask &t, uint16_t accent) {
  _tft.fillRect(cardX, barsY, cardW, kBar2Y + cardBarH - barsY, theme::bg);

  const PlanetInfo &p = t.planet;
  const CardRates r = cardRates(m, _targetIdx, t);

  if (p.valid && p.event.active) {
    // A defence is a tug of war over one bar: our share and theirs. The API
    // publishes only the pair, so the second bar is the first one's complement
    // — and its rate is therefore the mirror of the first's, not a second
    // independent measurement.
    const float held = p.event.defended();
    drawRateBar(barsY, held, theme::blue, r.have, r.pct);
    drawRateBar(kBar2Y, 100.0f - held, accent, r.have, -r.pct);
    return;
  }

  if (p.valid && taskIsLiberation(t.taskType)) {
    drawRateBar(kSoloBarY, p.liberation, theme::blue, r.have, r.pct);
    return;
  }

  // A defend objective with nothing attacking it has no progress to show: the
  // planet sits at full health, which is not the same as "0% done".
  drawIdleBar(kSoloBarY,
              p.valid ? String(F("NO ASSAULT IN PROGRESS"))
                      : String(F("AWAITING TELEMETRY")),
              theme::grey);
}

void HUDRenderer::drawVerdict(const HudModel &m, const OrderTask &t) {
  _tft.fillRect(cardX, verdictY, cardW, verdictH, theme::bg);

  const PlanetInfo &p = t.planet;
  const CardRates r = cardRates(m, _targetIdx, t);

  String left;
  uint16_t leftColor = theme::text;
  const GFXfont *leftFont = FONT_VALUE;
  char buf[32];
  if (p.valid && p.event.active) {
    snprintf(buf, sizeof(buf), "%.0f%% DEFENDED", p.event.defended());
    left = buf;
  } else if (p.valid && taskIsLiberation(t.taskType)) {
    snprintf(buf, sizeof(buf), "%.0f%% LIBERATED", p.liberation);
    left = buf;
  } else {
    const StatusLine st = objectiveStatus(t);
    left = st.text;
    leftColor = st.color;
  }

  // The verdict is only drawn when it is measured: it needs an assault to be
  // under way *and* two polls to compare. Without both there is nothing to say,
  // so the right-hand slot stays empty rather than guessing a side.
  int16_t leftW = cardW;
  if (p.valid && p.event.active && r.have) {
    const bool winning = r.pct >= 0.0f;
    const uint16_t c = winning ? theme::green : theme::red;
    const String word = winning ? String(F("WINNING")) : String(F("LOSING"));

    _tft.setFreeFont(FONT_LABEL);
    const int16_t wordW = _tft.textWidth(word.c_str());
    const int16_t blockW = icons::gaugeW + verdictIconGap + wordW;
    const int16_t blockX = cardX + cardW - blockW;

    textBox(blockX, verdictY, blockW, verdictH, theme::bg, FONT_LABEL, c, ML_DATUM,
            word, icons::gaugeW + verdictIconGap);
    _tft.drawBitmap(blockX, verdictY + (verdictH - icons::gaugeH) / 2, icons::gauge,
                    icons::gaugeW, icons::gaugeH, c);
    leftW = blockX - cardX - 12;
  }

  textBox(cardX, verdictY, leftW, verdictH, theme::bg, leftFont, leftColor, ML_DATUM,
          left);
}

void HUDRenderer::drawCard(const HudModel &m) {
  _targetSig = targetSignature(m, _targetIdx);

  const OrderTask *t = activeTask(m, _targetIdx);
  if (!t) {
    _tft.fillRect(cardX, objY, cardW, verdictY + verdictH - objY, theme::bg);
    textBox(cardX, idyY, cardW, idyH, theme::bg, FONT_VALUE, theme::grey, MC_DATUM,
            F("ORDER HAS NO TARGETS"));
    _clockSig = "";
    return;
  }

  // Whoever is attacking sets the card's accent; with nobody attacking it falls
  // back to the HUD's own gold.
  const uint16_t accent = t->planet.event.active
                              ? factionAccent(t->planet.event.faction)
                              : theme::gold;

  drawObjectiveBar(m, *t, accent);
  drawIdentity(*t, accent);
  drawAlertRibbon(*t, accent);
  drawScene(m, *t, accent);
  // The order's title has nowhere else to live now that the card's top bar
  // belongs to the objective, so it captions the scene panel.
  {
    const uint16_t base = lerp565(theme::panel, accent, 26);
    const int16_t textX = cardX + scenePad;
    const int16_t textW = cardX + cardW - scenePad - icons::crestW - scenePad - textX;
    String title = upper(m.order.title);
    _tft.setFreeFont(FONT_LABEL);
    while (title.length() > 1 && _tft.textWidth(title.c_str()) > textW) {
      title.remove(title.length() - 1);
    }
    textBox(textX, sceneY + sceneTitleDy, textW, sceneTitleH, base, FONT_LABEL,
            theme::gold, ML_DATUM, title);
  }
  drawProgress(m, *t, accent);
  drawVerdict(m, *t);

  // The objective bar was repainted under both clocks.
  _clockSig = "";
}

void HUDRenderer::drawCardClocks(const HudModel &m, time_t nowUtc) {
  if (!_cardMode || _flagW <= 0) return;

  // 1.6e9 ~= 2020-09; anything below that means NTP hasn't synced yet and a
  // countdown would be nonsense.
  const bool clockOk = nowUtc > 1600000000;

  String order = F("--");
  if (m.order.expiration > 0 && clockOk) {
    order = formatDuration((int64_t)m.order.expiration - (int64_t)nowUtc);
  }

  String victory;
  if (_victoryW > 0) {
    const OrderTask *t = activeTask(m, _targetIdx);
    victory = F("--");
    if (t && t->planet.event.active && t->planet.event.endTime > 0 && clockOk) {
      victory = formatDuration((int64_t)t->planet.event.endTime - (int64_t)nowUtc);
    }
  }

  const String sig = order + "|" + victory;
  if (sig == _clockSig) return;
  _clockSig = sig;

  textBox(_flagX, objY + 1, _flagW, objH - 2, theme::gold, FONT_LABEL, theme::flagInk,
          MC_DATUM, order);
  if (_victoryW > 0) {
    washText(_victoryX, objY + 1, _victoryW, objH - 2, FONT_LABEL, theme::text,
             MR_DATUM, victory);
  }
}

// ---------------------------------------------------------------------------
//  Body
// ---------------------------------------------------------------------------

void HUDRenderer::drawBody(const HudModel &m, time_t nowUtc) {
  // Clear the whole frame interior, then repaint the frame, since the corner
  // brackets are thicker than the 1px border we left standing.
  _tft.fillRect(frameX + 1, frameY + 1, frameW - 2, frameH - 2, theme::bg);
  drawFrame();

  // The card fills the frame on its own; every other screen keeps the plain
  // "SUPER EARTH" strip above its content.
  _cardMode = m.haveData && m.order.valid;
  if (!_cardMode)
    drawStatusHeader(m.campaign.valid ? String(F("LIBERATION")) : String());
  _wifiSig = -1;  // the repaint wiped the dot

  if (!m.haveData) {
    _tft.drawBitmap(padX + (contentW - icons::emblemLargeW) / 2, 96,
                    icons::emblemLarge, icons::emblemLargeW, icons::emblemLargeH,
                    theme::goldDim);
    textBox(padX, 150, contentW, 34, theme::bg, FONT_DISPLAY, theme::gold, MC_DATUM,
            F("ESTABLISHING UPLINK"));
    drawRule(rule3Y);
  } else if (_cardMode) {
    _targetSig = "";
    drawCard(m);
    drawRule(cardRuleY);
  } else if (m.campaign.valid) {
    // No rule3 here: the four-value strip runs to 278, well past rule3Y (260),
    // so the line landed across the digits. The strip's own column dividers
    // already separate it from the footer.
    drawCampaignBody(m);
  } else {
    drawIdleBody(m);
    drawRule(rule3Y);
  }

  // Force the self-updating regions to repaint into the freshly cleared area.
  _clockSig = "";
  _footerSig = "";
  if (_cardMode) drawCardClocks(m, nowUtc);
  drawFooter(m, nowUtc);
}

void HUDRenderer::drawCampaignBody(const HudModel &m) {
  const PlanetInfo &p = m.campaign;
  const uint16_t accent = factionAccent(p.owner);

  // --- identity: planet, sector, and who holds it --------------------------
  const int16_t bw = badgeWidth(p.owner);
  const int16_t badgeX = padX + contentW - bw;
  drawBadge(p.owner, badgeX, kCampBadgeY, kCampBadgeH);

  textBox(padX, kCampNameY, badgeX - padX - 8, kCampNameH, theme::bg, FONT_HEADLINE,
          theme::text, ML_DATUM, upper(p.name));
  textBox(padX, kCampSectorY, contentW, kCampSectorH, theme::bg, FONT_BODY,
          theme::grey, ML_DATUM, sectorLabel(p.sector));

  // --- biome plate ---------------------------------------------------------
  // Stored at half size and scaled up here; see tools/gen_biomes.py.
  const int8_t bi = biomeFromName(p.biome);
  const uint16_t *plate =
      (uint16_t *)pgm_read_ptr(&biomes::table[bi < 0 || bi >= biomes::kCount
                                                  ? kBiomeUnknown
                                                  : bi]);
  drawBiome(plate, biomes::kW, biomes::kH, padX, kCampBiomeY, contentW, kCampBiomeH);
  _tft.drawRect(padX, kCampBiomeY, contentW, kCampBiomeH, theme::cardEdge);

  // --- liberation ----------------------------------------------------------
  const RateSample &h = m.campaignHistory;
  float rate = 0.0f;
  const bool haveRate =
      h.valid && ratePerHour(p.liberation, p.observedAt, h.libPct, h.at, rate);
  drawRateBar(kCampBarY, p.liberation, accent, haveRate, rate);

  // "CONTROLLED" while the enemy still holds it, which is what the percentage
  // is actually measuring until the push lands.
  char pct[32];
  snprintf(pct, sizeof(pct), "%.4f%% LIBERATED", p.liberation);
  textBox(padX, kCampPctY, contentW, kCampPctH, theme::bg, FONT_VALUE, theme::text,
          ML_DATUM, pct);

  // --- four-value strip ----------------------------------------------------
  // Share of the galaxy's divers here, the head-count itself, the players'
  // push, and the enemy's regen. The last two are the two halves of the net
  // rate above: push minus regen is what the bar is moving at.
  const float regenPctPerHour =
      p.maxHealth > 0 ? p.regenPerSecond * 3600.0f * 100.0f / (float)p.maxHealth : 0.0f;
  const float pushPctPerHour = (haveRate ? rate : 0.0f) + regenPctPerHour;

  char share[12], here[16], push[16], regen[16];
  // Galaxy-wide count is a separate reading taken at a separate moment, so it
  // can legitimately be smaller than this planet's. Clamp rather than print an
  // arithmetically-correct 200050%.
  const uint32_t galaxy = m.war.valid ? m.war.playerCount : 0;
  uint32_t sharePct = galaxy ? (uint32_t)((p.playerCount * 100ULL) / galaxy) : 0U;
  if (sharePct > 100) sharePct = 100;
  snprintf(share, sizeof(share), "%u%%", (unsigned)sharePct);
  snprintf(here, sizeof(here), "%s", formatCount(p.playerCount).c_str());
  if (haveRate) snprintf(push, sizeof(push), "%.3f%%", pushPctPerHour);
  else          snprintf(push, sizeof(push), "--");
  snprintf(regen, sizeof(regen), "%.2f%%", regenPctPerHour);

  const int16_t colW = contentW / kCampStripCols;
  // "/H" on the two rates because they are per-hour and the values carry only
  // a percent sign; without it "2.593%" reads as a position, not a speed.
  const struct { const char *cap; const char *v; uint16_t c; } cols[kCampStripCols] = {
      {"SHARE",  share, theme::gold}, {"DIVERS",   here,  theme::text},
      {"PUSH /H", push, theme::blue}, {"REGEN /H", regen, accent},
  };
  const int16_t stripH = (kCampStripValY + kCampStripValH) - kCampStripY;
  for (int i = 0; i < kCampStripCols; i++) {
    const int16_t x = padX + i * colW;
    // nullptr font == TFT_eSPI's built-in 6x8 GLCD face; see setFreeFont().
    textBox(x, kCampStripY, colW - 6, kCampStripCapH, theme::bg, nullptr,
            theme::grey, ML_DATUM, cols[i].cap);
    textBox(x, kCampStripValY, colW - 6, kCampStripValH, theme::bg, FONT_LABEL,
            cols[i].c, ML_DATUM, cols[i].v);
    if (i) _tft.drawFastVLine(x - 4, kCampStripY + 2, stripH - 4, theme::cardEdge);
  }
}

void HUDRenderer::drawIdleBody(const HudModel &m) {
  // With no order to show, the emblem becomes the centrepiece and the galactic
  // war totals take over the tiles.
  _tft.drawBitmap(padX + (contentW - icons::emblemLargeW) / 2, 92, icons::emblemLarge,
                  icons::emblemLargeW, icons::emblemLargeH, theme::goldDim);
  // At 18pt this line is 463px, wider than the 440px content column, so it is
  // set at value size.
  textBox(padX, 146, contentW, 28, theme::bg, FONT_VALUE, theme::gold, MC_DATUM,
          F("NO ACTIVE MAJOR ORDER"));

  drawTile(0, icons::divers, icons::diversW, icons::diversH,
           m.war.valid ? formatCompact(m.war.playerCount) : String("--"), theme::gold);
  drawTile(1, icons::skull, icons::skullW, icons::skullH,
           m.war.valid ? formatCompact(m.war.totalKills) : String("--"), theme::gold);
  drawTile(2, icons::check, icons::checkW, icons::checkH,
           m.war.valid ? String(m.war.missionSuccessRate) + "%" : String("--"),
           theme::gold);
}

void HUDRenderer::drawFooter(const HudModel &m, time_t nowUtc) {
  String synced;
  if (!m.haveData) {
    synced = F("NO DATA YET");
  } else {
    char t[8] = "--:--";
    if (m.lastSuccess > 0) {
      // Shift the epoch, then read it back as if it were UTC: that yields
      // local wall-clock time without depending on a TZ database being
      // present, and without touching the countdowns, which are durations.
      struct tm tmv;
      time_t ls = m.lastSuccess + (time_t)m.utcOffsetMin * 60;
      gmtime_r(&ls, &tmv);
      snprintf(t, sizeof(t), "%02d:%02d", tmv.tm_hour, tmv.tm_min);
    }
    synced = (m.stale ? String(F("STALE ")) : String(F("SYNCED "))) + t;
  }

  // Reward, as a medal icon and a bare number — "REWARD n MEDALS" spelled out
  // was the single wordiest thing on the HUD for one integer of information.
  String reward;
  if (m.haveData && m.order.valid && m.order.rewardAmount > 0) {
    reward = String(m.order.rewardAmount);
  }

  // Divers on the planet currently on screen. Only the card has a planet.
  String divers;
  if (_cardMode) {
    const OrderTask *t = activeTask(m, _targetIdx);
    divers = (t && t->planet.valid) ? formatCount(t->planet.playerCount) : String("--");
  }

  const String sig = synced + "|" + reward + "|" + divers + "|" + (m.stale ? "1" : "0");
  if (sig == _footerSig) return;
  _footerSig = sig;

  const int16_t y = _cardMode ? cardFootY : footerY;
  const int16_t h = _cardMode ? cardFootH : footerH;
  const uint16_t syncColor = m.stale ? theme::goldMute : theme::grey;

  _tft.setFreeFont(FONT_BODY);

  // --- left: divers present -----------------------------------------------
  if (_cardMode) {
    // Cleared to a fixed width rather than to the width of this frame's text:
    // the count is no longer zero-padded, so "9,412" following "18,204" would
    // otherwise leave the old digits' tail on screen.
    const int16_t w = icons::diverW + footIconGap + kCountBoxW;
    textBox(cardX, y, w, h, theme::bg, FONT_BODY, theme::gold, ML_DATUM, divers,
            icons::diverW + footIconGap);
    _tft.drawBitmap(cardX, y + (h - icons::diverH) / 2, icons::diver, icons::diverW,
                    icons::diverH, theme::gold);
  }

  // --- right: last sync, with the WiFi dot beyond it in card mode ----------
  const int16_t syncR = _cardMode ? contentR - (2 * footDotR + 1) - 8 : contentR;
  textBox(syncR - 150, y, 150, h, theme::bg, FONT_BODY, syncColor, MR_DATUM, synced);
  _wifiSig = -1;  // the box above may have clipped the dot

  // --- centre: the order's reward -----------------------------------------
  if (reward.length()) {
    const int16_t w = icons::medalW + footerIconGap + _tft.textWidth(reward.c_str());
    const int16_t x = _cardMode ? cardX + (cardW - w) / 2 : contentR - w;
    textBox(x, y, w, h, theme::bg, FONT_BODY, theme::gold, ML_DATUM, reward,
            icons::medalW + footerIconGap);
    _tft.drawBitmap(x, y + (h - icons::medalH) / 2, icons::medal, icons::medalW,
                    icons::medalH, theme::gold);
  }
  (void)nowUtc;
}

// ---------------------------------------------------------------------------
//  Public entry points
// ---------------------------------------------------------------------------

void HUDRenderer::updateTargetCycle(const HudModel &m) {
  const int count = (m.haveData && m.order.valid) ? m.order.taskCount : 0;
  if (count <= 1) {
    // Nothing to cycle. Keep the stamp fresh so the first multi-target order to
    // arrive gets a full dwell before it advances.
    _targetIdx = 0;
    _targetSwitchMs = millis();
    return;
  }
  if (_targetIdx >= (uint8_t)count) _targetIdx = 0;

  const uint32_t nowMs = millis();
  if ((uint32_t)(nowMs - _targetSwitchMs) >= kTargetCycleMs) {
    _targetIdx = (uint8_t)((_targetIdx + 1) % count);
    _targetSwitchMs = nowMs;
  }
}

void HUDRenderer::update(const HudModel &m, time_t nowUtc) {
  if (!_chromeDrawn) {
    _tft.fillScreen(theme::bg);
    drawFrame();
    // The rest is left to drawBody(), which is about to run: the cleared
    // _contentSig guarantees it.
    _chromeDrawn = true;
    _contentSig = "";
    _targetSig = "";
    _wifiSig = -1;
  }

  updateTargetCycle(m);

  const String sig = contentSignature(m);
  if (sig != _contentSig) {
    _contentSig = sig;
    drawBody(m, nowUtc);
  } else if (_cardMode && targetSignature(m, _targetIdx) != _targetSig) {
    // The carousel moved on, or this target's planet data did.
    drawCard(m);
  }

  if (_cardMode) drawCardClocks(m, nowUtc);
  drawFooter(m, nowUtc);
  drawWifi(m.wifiUp);
}

void HUDRenderer::showBoot(const char *status) {
  invalidate();
  _cardMode = false;
  _tft.fillScreen(theme::bg);
  drawFrame();
  drawStatusHeader();
  // The Helldivers II title mark, boot screen only -- the idle screen keeps
  // the SEAF emblem as its own centrepiece. Cut at the full 440px content
  // width so it carries the screen; only scaled and recoloured, never redrawn.
  _tft.drawBitmap(padX, 48, icons::hd2LogoBoot, icons::hd2LogoBootW,
                  icons::hd2LogoBootH, theme::gold);
  textBox(padX, 232, contentW, 22, theme::bg, FONT_VALUE, theme::text, MC_DATUM,
          F("MAJOR ORDER MONITOR"));
  textBox(padX, 264, contentW, 20, theme::bg, FONT_BODY, theme::grey, MC_DATUM,
          String(status));
  // Next update() must repaint from scratch.
  _chromeDrawn = false;
}

void HUDRenderer::showPortal(const char *ssid, const char *pass) {
  invalidate();
  _cardMode = false;
  _tft.fillScreen(theme::bg);
  drawFrame();
  drawStatusHeader();
  textBox(padX, 60, contentW, 30, theme::bg, FONT_DISPLAY, theme::gold, MC_DATUM,
          F("WIFI SETUP"));
  textBox(padX, 104, contentW, 20, theme::bg, FONT_BODY, theme::text, MC_DATUM,
          F("Join this network from a phone or laptop,"));
  textBox(padX, 124, contentW, 20, theme::bg, FONT_BODY, theme::text, MC_DATUM,
          F("then set WiFi and UTC offset in the page that opens."));

  drawStatBox(padX, statY, kStatW, statH, F("NETWORK"), String(ssid), theme::gold);
  drawStatBox(padX + kStatW + statGap, statY, kStatW, statH, F("PASSWORD"),
              String(pass), theme::gold);

  textBox(padX, 224, contentW, 20, theme::bg, FONT_BODY, theme::grey, MC_DATUM,
          F("If no page opens, browse to 192.168.4.1"));
  _chromeDrawn = false;
}
