#include "hud_renderer.h"

#include "config.h"
#include "hd2_api.h"    // formatDuration / formatCompact
#include "hud_fonts.h"  // must be included by exactly one .cpp
#include "hud_icons.h"  // generated by tools/gen_icons.py

using namespace layout;

// ---------------------------------------------------------------------------
//  Icons
// ---------------------------------------------------------------------------

namespace {

struct IconRef {
  const uint8_t *bits;
  int16_t w, h;
};

// The badge icon for a planet owner. Matched on a lowercased prefix so both
// the singular and plural spellings the API uses ("Automaton", "Terminids")
// land on the same icon.
IconRef factionIcon(const String &faction) {
  String f = faction;
  f.toLowerCase();
  if (f.startsWith("automaton"))
    return {icons::automaton, icons::automatonW, icons::automatonH};
  if (f.startsWith("terminid"))
    return {icons::terminid, icons::terminidW, icons::terminidH};
  if (f.startsWith("illuminate"))
    return {icons::illuminate, icons::illuminateW, icons::illuminateH};
  if (f.startsWith("human"))
    return {icons::emblemBadge, icons::emblemBadgeW, icons::emblemBadgeH};
  return {nullptr, 0, 0};  // unknown owner: badge falls back to text only
}

}  // namespace

// Where "SUPER EARTH" starts, once the emblem has taken its slot.
static constexpr int16_t kHeaderTextInset = icons::emblemW + headerIconGap;

// Where the planet name starts, once the crosshair has taken its slot. The
// crosshair replaces what used to be a "TARGET" text label.
static constexpr int16_t kTargetNameX = padX + icons::targetW + targetIconGap;

// ---------------------------------------------------------------------------
//  Small helpers
// ---------------------------------------------------------------------------

static String upper(const String &s) {
  String t = s;
  t.toUpperCase();
  return t;
}

// Humans holding a planet is good news; anyone else gets the red treatment.
static uint16_t factionColor(const String &faction) {
  return faction.equalsIgnoreCase("Humans") ? theme::green : theme::red;
}

// Anchor point inside a w*h box for a given TFT_eSPI datum.
static void datumAnchor(uint8_t datum, int16_t w, int16_t h, int16_t &ax, int16_t &ay) {
  switch (datum) {
    case TC_DATUM: ax = w / 2; ay = 0;     break;
    case TR_DATUM: ax = w;     ay = 0;     break;
    case ML_DATUM: ax = 0;     ay = h / 2; break;
    case MC_DATUM: ax = w / 2; ay = h / 2; break;
    case MR_DATUM: ax = w;     ay = h / 2; break;
    default:       ax = 0;     ay = 0;     break;  // TL_DATUM
  }
}

// Everything that, when it changes, warrants a full body repaint. The
// countdown, WiFi dot and footer are deliberately excluded — they update
// themselves through their own small sprites.
static String contentSignature(const HudModel &m) {
  if (!m.haveData) return F("boot");
  String s;
  s.reserve(128);
  if (!m.order.valid) {
    s = F("idle|");
  } else {
    s = m.order.title;
    s += '|';
    s += m.planet.name;
    s += '|';
    s += m.planet.sector;
    s += '|';
    s += m.planet.owner;
    s += '|';
    s += String((int)(m.planet.liberation * 10.0f));  // 0.1% resolution
    s += '|';
    s += String(m.planet.playerCount);
    s += '|';
  }
  s += String(m.war.playerCount);
  s += '|';
  s += String(m.war.missionSuccessRate);
  s += '|';
  s += formatCompact(m.war.totalKills);
  return s;
}

// Geometry of the three icon tiles that make up the stat row, and of the
// two-up boxes on the WiFi setup screen.
static constexpr int16_t kTileW = (contentW - 2 * tileGap) / 3;  // 142
static constexpr int16_t kStatW = (contentW - statGap) / 2;      // 216
static constexpr int16_t kStatInsetX = 12;
static constexpr int16_t kStatValueDy = 21;
static constexpr int16_t kStatValueH = 20;

// ---------------------------------------------------------------------------
//  Lifecycle
// ---------------------------------------------------------------------------

void HUDRenderer::begin() {
  _tft.init();
  // Rotation 1 turns the native 320x480 portrait panel into 480x320 landscape.
  // If the image is upside down for how the board sits on your desk, use 3.
  _tft.setRotation(1);
  _tft.fillScreen(theme::bg);

  // TFT_BL is driven by TFT_eSPI when TFT_BL is defined, but do it explicitly
  // so the backlight is on even if that define is later removed.
#ifdef TFT_BL
  pinMode(TFT_BL, OUTPUT);
  digitalWrite(TFT_BL, TFT_BACKLIGHT_ON);
#endif

  invalidate();
}

void HUDRenderer::invalidate() {
  _chromeDrawn = false;
  _contentSig = "";
  _countdownSig = "";
  _footerSig = "";
  _wifiSig = -1;
}

// ---------------------------------------------------------------------------
//  Primitives
// ---------------------------------------------------------------------------

void HUDRenderer::textBox(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t bg,
                          const GFXfont *font, uint16_t fg, uint8_t datum,
                          const String &s, int16_t inset) {
  TFT_eSprite spr(&_tft);
  spr.setColorDepth(16);
  if (spr.createSprite(w, h)) {
    spr.fillSprite(bg);
    spr.setFreeFont(font);
    spr.setTextColor(fg, bg);
    spr.setTextDatum(datum);
    int16_t ax, ay;
    datumAnchor(datum, w, h, ax, ay);
    if (datum == TL_DATUM || datum == ML_DATUM) ax += inset;
    if (datum == TR_DATUM || datum == MR_DATUM) ax -= inset;
    spr.drawString(s.c_str(), ax, ay);
    spr.pushSprite(x, y);
    spr.deleteSprite();
    return;
  }
  // Sprite allocation failed (heap pressure) — fall back to direct drawing.
  // Slight flicker, but never a blank region.
  _tft.fillRect(x, y, w, h, bg);
  _tft.setFreeFont(font);
  _tft.setTextColor(fg, bg);
  _tft.setTextDatum(datum);
  int16_t ax, ay;
  datumAnchor(datum, w, h, ax, ay);
  if (datum == TL_DATUM || datum == ML_DATUM) ax += inset;
  if (datum == TR_DATUM || datum == MR_DATUM) ax -= inset;
  _tft.drawString(s.c_str(), x + ax, y + ay);
}

void HUDRenderer::drawRule(int16_t y) {
  _tft.drawFastHLine(padX, y, contentW, theme::goldDim);
}

int16_t HUDRenderer::tileX(int i) {
  return padX + i * (kTileW + tileGap);
}

void HUDRenderer::drawTile(int i, const uint8_t *icon, int16_t iw, int16_t ih,
                           const String &value, uint16_t valueColor) {
  const int16_t x = tileX(i);
  _tft.fillRect(x, tileY, kTileW, tileH, theme::panel);
  _tft.drawRect(x, tileY, kTileW, tileH, theme::goldDim);
  // The icon stands in for what used to be an ALL-CAPS label, so it is drawn
  // at label weight rather than value weight.
  _tft.drawBitmap(x + tileInsetX, tileY + tileIconDy, icon, iw, ih, theme::goldDim);
  drawTileValue(i, value, valueColor);
}

void HUDRenderer::drawTileValue(int i, const String &value, uint16_t color) {
  // Drop a size rather than run off the edge of the tile ("EXPIRED", or a
  // player count that has gone six digits).
  _tft.setFreeFont(FONT_VALUE);
  const GFXfont *font = (_tft.textWidth(value.c_str()) > kTileW - 2 * tileInsetX)
                            ? FONT_LABEL
                            : FONT_VALUE;
  textBox(tileX(i) + 1, tileY + tileValueDy, kTileW - 2, tileValueH, theme::panel,
          font, color, ML_DATUM, value, tileInsetX - 1);
}

void HUDRenderer::drawStatBox(int16_t x, int16_t y, int16_t w, int16_t h,
                              const String &label, const String &value,
                              uint16_t valueColor) {
  _tft.fillRect(x, y, w, h, theme::panel);
  _tft.drawRect(x, y, w, h, theme::goldDim);
  textBox(x + 1, y + 5, w - 2, 15, theme::panel, FONT_LABEL, theme::grey, ML_DATUM,
          label, kStatInsetX - 1);

  // Drop a size rather than run off the edge of the box (long values show up
  // in the WiFi-setup screen, and for very large player counts).
  _tft.setFreeFont(FONT_VALUE);
  const GFXfont *valueFont =
      (_tft.textWidth(value.c_str()) > w - 2 * kStatInsetX) ? FONT_LABEL : FONT_VALUE;
  textBox(x + 1, y + kStatValueDy, w - 2, kStatValueH, theme::panel, valueFont,
          valueColor, ML_DATUM, value, kStatInsetX - 1);
}

void HUDRenderer::drawProgressBar(float pct, bool known) {
  TFT_eSprite spr(&_tft);
  spr.setColorDepth(16);
  if (!spr.createSprite(contentW, barH)) {
    _tft.fillRect(padX, barY, contentW, barH, theme::track);
    _tft.drawRect(padX, barY, contentW, barH, theme::goldDim);
    return;
  }

  spr.fillSprite(theme::track);
  if (known) {
    const int16_t fillW = (int16_t)((contentW - 2) * (pct / 100.0f) + 0.5f);
    if (fillW > 0) spr.fillRect(1, 1, fillW, barH - 2, theme::blue);
  }
  spr.drawRect(0, 0, contentW, barH, theme::goldDim);

  // Centred label, deliberately short so it stays legible where it crosses
  // the fill/track boundary. At 18pt it is the loudest number on the HUD,
  // which is the point — it is the one figure worth reading from across a
  // room.
  char buf[24];
  if (known) {
    snprintf(buf, sizeof(buf), "%d%% LIBERATED", (int)(pct + 0.5f));
  } else {
    snprintf(buf, sizeof(buf), "AWAITING TELEMETRY");
  }
  spr.setFreeFont(FONT_DISPLAY);
  spr.setTextDatum(MC_DATUM);
  spr.setTextColor(known ? theme::text : theme::grey);
  spr.drawString(buf, contentW / 2, barH / 2);

  spr.pushSprite(padX, barY);
  spr.deleteSprite();
}

int16_t HUDRenderer::badgeWidth(const String &faction) {
  const String label = upper(faction.length() ? faction : String("UNKNOWN"));
  const IconRef ic = factionIcon(faction);

  _tft.setFreeFont(FONT_LABEL);
  int16_t w = _tft.textWidth(label.c_str()) + 2 * badgePadX;
  if (ic.bits) w += ic.w + badgeIconGap;
  return w > badgeMaxW ? badgeMaxW : w;
}

void HUDRenderer::drawBadge(const String &faction) {
  const String label = upper(faction.length() ? faction : String("UNKNOWN"));
  const uint16_t c = factionColor(faction);
  const IconRef ic = factionIcon(faction);

  const int16_t w = badgeWidth(faction);
  const int16_t x = contentR - w;
  const int16_t y = targetY + (targetH - badgeH) / 2;

  _tft.fillRect(x, y, w, badgeH, theme::bg);
  _tft.drawRect(x, y, w, badgeH, c);

  if (ic.bits) {
    // Icon then label, left-aligned as a pair. Since the badge is sized to
    // fit exactly, that reads as centred. textBox() clears the icon slot on
    // its way past, so the bitmap goes down afterwards.
    textBox(x + 1, y + 1, w - 2, badgeH - 2, theme::bg, FONT_LABEL, c, ML_DATUM,
            label, badgePadX + ic.w + badgeIconGap - 1);
    _tft.drawBitmap(x + badgePadX, y + (badgeH - ic.h) / 2, ic.bits, ic.w, ic.h, c);
  } else {
    textBox(x + 1, y + 1, w - 2, badgeH - 2, theme::bg, FONT_LABEL, c, MC_DATUM, label);
  }
}

// ---------------------------------------------------------------------------
//  Chrome — outer frame, corner brackets, header row
// ---------------------------------------------------------------------------

void HUDRenderer::drawChrome() {
  const int16_t x0 = frameX, y0 = frameY;
  const int16_t x1 = frameX + frameW - 1, y1 = frameY + frameH - 1;

  _tft.drawRect(x0, y0, frameW, frameH, theme::goldDim);

  // Squared-off corner accents: two arms per corner, brighter and thicker
  // than the frame itself.
  const int16_t L = bracketLen, T = bracketThick;
  // top-left
  _tft.fillRect(x0, y0, L, T, theme::gold);
  _tft.fillRect(x0, y0, T, L, theme::gold);
  // top-right
  _tft.fillRect(x1 - L + 1, y0, L, T, theme::gold);
  _tft.fillRect(x1 - T + 1, y0, T, L, theme::gold);
  // bottom-left
  _tft.fillRect(x0, y1 - T + 1, L, T, theme::gold);
  _tft.fillRect(x0, y1 - L + 1, T, L, theme::gold);
  // bottom-right
  _tft.fillRect(x1 - L + 1, y1 - T + 1, L, T, theme::gold);
  _tft.fillRect(x1 - T + 1, y1 - L + 1, T, L, theme::gold);

  // The text box spans the emblem slot too, so it clears it; the emblem is
  // then drawn into that cleared space.
  textBox(padX, headerY, 200, headerH, theme::bg, FONT_LABEL, theme::gold, ML_DATUM,
          F("SUPER EARTH"), kHeaderTextInset);
  _tft.drawBitmap(padX, headerY + (headerH - icons::emblemH) / 2, icons::emblem,
                  icons::emblemW, icons::emblemH, theme::gold);
  drawRule(rule1Y);

  _chromeDrawn = true;
}

void HUDRenderer::drawWifi(bool up) {
  const int8_t sig = up ? 1 : 0;
  if (sig == _wifiSig) return;
  _wifiSig = sig;

  const uint16_t c = up ? theme::green : theme::red;
  const int16_t dotR = 5;
  const int16_t dotCx = contentR - dotR;
  const int16_t cy = headerY + headerH / 2;

  // Label right-aligned just left of the dot.
  textBox(contentR - 110, headerY, 110 - (2 * dotR + 6), headerH, theme::bg,
          FONT_LABEL, c, MR_DATUM, up ? F("WIFI") : F("OFFLINE"));

  _tft.fillRect(dotCx - dotR, cy - dotR, 2 * dotR + 1, 2 * dotR + 1, theme::bg);
  _tft.fillCircle(dotCx, cy, dotR, c);
}

// ---------------------------------------------------------------------------
//  Body
// ---------------------------------------------------------------------------

void HUDRenderer::drawBody(const HudModel &m, time_t nowUtc) {
  // Clear everything below the header rule, then repaint the chrome, since
  // the corner brackets are thicker than the 1px frame we left standing.
  _tft.fillRect(frameX + 1, rule1Y + 1, frameW - 2,
                frameY + frameH - rule1Y - 2, theme::bg);
  drawChrome();
  _wifiSig = -1;  // the header repaint wiped the dot

  if (!m.haveData) {
    _tft.drawBitmap(padX + (contentW - icons::emblemLargeW) / 2, 96,
                    icons::emblemLarge, icons::emblemLargeW, icons::emblemLargeH,
                    theme::goldDim);
    textBox(padX, 150, contentW, 34, theme::bg, FONT_DISPLAY, theme::gold, MC_DATUM,
            F("ESTABLISHING UPLINK"));
  } else if (m.order.valid) {
    drawOrderBody(m);
  } else {
    drawIdleBody(m);
  }

  drawRule(rule3Y);

  // Force the self-updating regions to repaint into the freshly cleared area.
  _countdownSig = "";
  _footerSig = "";
  if (m.haveData && m.order.valid) drawCountdown(m, nowUtc);
  drawFooter(m, nowUtc);
}

void HUDRenderer::drawOrderBody(const HudModel &m) {
  // --- title --------------------------------------------------------------
  // The briefing paragraph used to sit under this. It restated the target the
  // row below already names, so it is gone and the space went to the graphics.
  textBox(padX, titleY, contentW, titleH, theme::bg, FONT_DISPLAY, theme::gold,
          ML_DATUM, upper(m.order.title));

  drawRule(rule2Y);

  // --- target planet ------------------------------------------------------
  _tft.drawBitmap(padX, targetY + (targetH - icons::targetH) / 2, icons::target,
                  icons::targetW, icons::targetH, theme::gold);

  if (m.planet.valid) {
    drawBadge(m.planet.owner);

    // Width left for the planet name between the crosshair and the badge.
    const int16_t rowR = contentR - badgeWidth(m.planet.owner) - badgeGap;
    const int16_t availW = rowR - kTargetNameX;

    // Drop a size if the name doesn't fit (e.g. "Angel's Venture").
    _tft.setFreeFont(FONT_DISPLAY);
    const GFXfont *nameFont = FONT_DISPLAY;
    int16_t nameW = _tft.textWidth(m.planet.name.c_str());
    if (nameW > availW) {
      nameFont = FONT_VALUE;
      _tft.setFreeFont(FONT_VALUE);
      nameW = _tft.textWidth(m.planet.name.c_str());
    }
    textBox(kTargetNameX, targetY, availW, targetH, theme::bg, nameFont, theme::text,
            ML_DATUM, m.planet.name);

    // Sector, folded down from a full subtitle line to a small grey tag on the
    // same row — and dropped outright when a long planet name has taken the
    // space. It is flavour, not data, so losing it costs nothing.
    if (m.planet.sector.length()) {
      const String tag = upper(m.planet.sector);
      _tft.setFreeFont(FONT_BODY);
      const int16_t tagW = _tft.textWidth(tag.c_str());
      if (nameW + tagGap + tagW <= availW) {
        textBox(rowR - tagW, targetY, tagW, targetH, theme::bg, FONT_BODY,
                theme::grey, MR_DATUM, tag);
      }
    }

    drawProgressBar(m.planet.liberation, true);
  } else {
    // The order has no planet-scoped task, or the planet lookup failed.
    textBox(kTargetNameX, targetY, contentR - kTargetNameX, targetH, theme::bg,
            FONT_VALUE, theme::grey, ML_DATUM,
            m.order.planetIndex >= 0 ? F("PLANET DATA UNAVAILABLE")
                                     : F("GALAXY-WIDE OBJECTIVE"));
    drawProgressBar(0.0f, false);
  }

  // --- icon tiles ---------------------------------------------------------
  // Tile 0's value is painted by drawCountdown(); pass a placeholder here.
  drawTile(0, icons::clock, icons::clockW, icons::clockH, "", theme::gold);
  drawTile(1, icons::divers, icons::diversW, icons::diversH,
           m.planet.valid ? formatCompact(m.planet.playerCount) : String("--"),
           theme::gold);
  drawTile(2, icons::skull, icons::skullW, icons::skullH,
           m.war.valid ? formatCompact(m.war.totalKills) : String("--"), theme::gold);
}

void HUDRenderer::drawIdleBody(const HudModel &m) {
  // With no order to show, the emblem becomes the centrepiece and the galactic
  // war totals take over the tiles.
  _tft.drawBitmap(padX + (contentW - icons::emblemLargeW) / 2, 92, icons::emblemLarge,
                  icons::emblemLargeW, icons::emblemLargeH, theme::goldDim);
  // At 18pt this line is 463px, wider than the 440px content column, so it is
  // set at value size.
  textBox(padX, 146, contentW, 28, theme::bg, FONT_VALUE, theme::gold, MC_DATUM,
          F("NO ACTIVE MAJOR ORDER"));

  drawTile(0, icons::divers, icons::diversW, icons::diversH,
           m.war.valid ? formatCompact(m.war.playerCount) : String("--"), theme::gold);
  drawTile(1, icons::skull, icons::skullW, icons::skullH,
           m.war.valid ? formatCompact(m.war.totalKills) : String("--"), theme::gold);
  drawTile(2, icons::check, icons::checkW, icons::checkH,
           m.war.valid ? String(m.war.missionSuccessRate) + "%" : String("--"),
           theme::gold);
}

void HUDRenderer::drawCountdown(const HudModel &m, time_t nowUtc) {
  String s;
  // 1.6e9 ~= 2020-09; anything below that means NTP hasn't synced yet and the
  // countdown would be nonsense.
  if (m.order.expiration > 0 && nowUtc > 1600000000) {
    s = formatDuration((int64_t)m.order.expiration - (int64_t)nowUtc);
  } else {
    s = "--";
  }
  if (s == _countdownSig) return;
  _countdownSig = s;

  drawTileValue(0, s, (s == "EXPIRED") ? theme::red : theme::gold);
}

void HUDRenderer::drawFooter(const HudModel &m, time_t nowUtc) {
  String left;
  if (!m.haveData) {
    left = "NO DATA YET";
  } else {
    char t[8] = "--:--";
    if (m.lastSuccess > 0) {
      // Shift the epoch, then read it back as if it were UTC: that yields
      // local wall-clock time without depending on a TZ database being
      // present, and without touching the countdown, which is a duration.
      struct tm tmv;
      time_t ls = m.lastSuccess + (time_t)m.utcOffsetMin * 60;
      gmtime_r(&ls, &tmv);
      snprintf(t, sizeof(t), "%02d:%02d", tmv.tm_hour, tmv.tm_min);
    }
    left = (m.stale ? String("STALE - LAST ") : String("SYNCED ")) + t;
  }

  // Reward, as a medal icon and a bare number — "REWARD n MEDALS" spelled out
  // was the single wordiest thing on the HUD for one integer of information.
  String reward;
  if (m.haveData && m.order.valid && m.order.rewardAmount > 0) {
    reward = String(m.order.rewardAmount);
  }

  const String sig = left + "|" + reward + "|" + (m.stale ? "1" : "0");
  if (sig == _footerSig) return;
  _footerSig = sig;

  textBox(padX, footerY, contentW / 2, footerH, theme::bg, FONT_BODY,
          m.stale ? theme::goldMute : theme::grey, ML_DATUM, left);

  _tft.setFreeFont(FONT_BODY);
  const int16_t rewardW =
      reward.length() ? icons::medalW + footerIconGap + _tft.textWidth(reward.c_str())
                      : 0;
  textBox(contentR - contentW / 2, footerY, contentW / 2, footerH, theme::bg,
          FONT_BODY, theme::gold, MR_DATUM, reward);
  if (reward.length()) {
    _tft.drawBitmap(contentR - rewardW, footerY + (footerH - icons::medalH) / 2,
                    icons::medal, icons::medalW, icons::medalH, theme::gold);
  }
  (void)nowUtc;
}

// ---------------------------------------------------------------------------
//  Public entry points
// ---------------------------------------------------------------------------

void HUDRenderer::update(const HudModel &m, time_t nowUtc) {
  if (!_chromeDrawn) {
    _tft.fillScreen(theme::bg);
    drawChrome();
    _contentSig = "";
    _wifiSig = -1;
  }

  const String sig = contentSignature(m);
  if (sig != _contentSig) {
    _contentSig = sig;
    drawBody(m, nowUtc);
  }

  drawWifi(m.wifiUp);
  if (m.haveData && m.order.valid) drawCountdown(m, nowUtc);
  drawFooter(m, nowUtc);
}

void HUDRenderer::showBoot(const char *status) {
  invalidate();
  _tft.fillScreen(theme::bg);
  drawChrome();
  textBox(padX, 120, contentW, 34, theme::bg, FONT_DISPLAY, theme::gold, MC_DATUM,
          F("SUPER EARTH"));
  textBox(padX, 158, contentW, 20, theme::bg, FONT_LABEL, theme::text, MC_DATUM,
          F("MAJOR ORDER MONITOR"));
  textBox(padX, 196, contentW, 20, theme::bg, FONT_BODY, theme::grey, MC_DATUM,
          String(status));
  // Next update() must repaint from scratch.
  _chromeDrawn = false;
}

void HUDRenderer::showPortal(const char *ssid, const char *pass) {
  invalidate();
  _tft.fillScreen(theme::bg);
  drawChrome();
  textBox(padX, 60, contentW, 30, theme::bg, FONT_DISPLAY, theme::gold, MC_DATUM,
          F("WIFI SETUP"));
  textBox(padX, 104, contentW, 20, theme::bg, FONT_BODY, theme::text, MC_DATUM,
          F("Join this network from a phone or laptop,"));
  textBox(padX, 124, contentW, 20, theme::bg, FONT_BODY, theme::text, MC_DATUM,
          F("then set WiFi and UTC offset in the page that opens."));

  drawStatBox(padX, statY, kStatW, statH, F("NETWORK"), String(ssid), theme::gold);
  drawStatBox(padX + kStatW + statGap, statY, kStatW, statH, F("PASSWORD"),
              String(pass), theme::gold);

  textBox(padX, 224, contentW, 20, theme::bg, FONT_BODY, theme::grey, MC_DATUM,
          F("If no page opens, browse to 192.168.4.1"));
  _chromeDrawn = false;
}
