// ---------------------------------------------------------------------------
//  Helldivers 2 — Major Order Desk Monitor
//
//  Standalone read-only status display for the current Major Order, running on
//  a Hosyond 4.0" 320x480 ESP32-32E board (ST7796S over SPI).
//
//  Flow:  boot -> WiFiManager (captive portal on first run) -> NTP -> poll the
//         Helldivers 2 Community API every 5 minutes -> paint the HUD.
//
//  Wiring/pin configuration lives in platformio.ini. Layout, palette and
//  timing knobs live in src/config.h.
// ---------------------------------------------------------------------------
#include <Arduino.h>
#include <Preferences.h>
#include <WiFi.h>
#include <WiFiManager.h>

#include "config.h"
#include "hd2_api.h"
#include "hd2_ota.h"
#include "hud_audio.h"
#include "hud_audio_clip.h"  // generated by tools/gen_audio_clip.py
#include "hud_renderer.h"
#include "hud_storage.h"
#include "hud_touch.h"

static HUDRenderer hud;
static HD2Api api;
static HD2Ota ota;
static HudModel model;
static Preferences prefs;

// Poll scheduling. `pollDueMs` is the next attempt; `backoffS` grows only
// while polls are failing and resets on the first success.
static uint32_t pollDueMs = 0;
static uint32_t backoffS = kBackoffMinS;
static uint32_t wifiRetryDueMs = 0;

// ---------------------------------------------------------------------------
//  Time
// ---------------------------------------------------------------------------

// --- UTC offset -------------------------------------------------------------
//
// The device clock stays on UTC; the offset is applied only where a clock time
// is drawn. It is entered in the WiFi setup portal as an hours[:minutes]
// string, which is what people know their timezone as, and stored in NVS as a
// plain minute count.

// Parses "-6", "+5:30", "5.75", "-3:45". Returns false on anything else.
static bool parseUtcOffset(const char *s, int16_t &outMinutes) {
  if (!s) return false;
  while (*s == ' ') s++;

  int sign = 1;
  if (*s == '+' || *s == '-') {
    if (*s == '-') sign = -1;
    s++;
  }
  if (!isdigit((unsigned char)*s)) return false;

  long hours = 0;
  while (isdigit((unsigned char)*s)) hours = hours * 10 + (*s++ - '0');

  long minutes = 0;
  if (*s == ':') {
    s++;
    if (!isdigit((unsigned char)*s)) return false;
    while (isdigit((unsigned char)*s)) minutes = minutes * 10 + (*s++ - '0');
    if (minutes > 59) return false;
  } else if (*s == '.' || *s == ',') {
    // Fractional hours, the way UTC+5.5 is often written.
    s++;
    long frac = 0, scale = 1;
    if (!isdigit((unsigned char)*s)) return false;
    while (isdigit((unsigned char)*s)) {
      frac = frac * 10 + (*s++ - '0');
      scale *= 10;
    }
    minutes = (frac * 60 + scale / 2) / scale;
  }
  while (*s == ' ') s++;
  if (*s != '\0') return false;

  const long total = sign * (hours * 60 + minutes);
  if (total < kUtcOffsetMinutesMin || total > kUtcOffsetMinutesMax) return false;
  outMinutes = (int16_t)total;
  return true;
}

// Inverse of the above, for pre-filling the portal field: "0", "-6", "+5:30".
static void formatUtcOffset(int16_t minutes, char *out, size_t n) {
  const char *sign = minutes < 0 ? "-" : (minutes > 0 ? "+" : "");
  const int mag = abs((int)minutes);
  if (mag % 60 == 0) {
    snprintf(out, n, "%s%d", sign, mag / 60);
  } else {
    snprintf(out, n, "%s%d:%02d", sign, mag / 60, mag % 60);
  }
}

// The /api/v1/war payload carries a `now` field, but it is not a usable wall
// clock (it reports a 1972 date), so the expiration countdown is driven by
// NTP instead. Everything is kept in UTC; the API's timestamps are UTC too.
static void syncClock() {
  configTime(0, 0, "pool.ntp.org", "time.google.com", "time.cloudflare.com");
  const uint32_t deadline = millis() + 15000;
  while (time(nullptr) < 1600000000 && millis() < deadline) {
    delay(250);
  }
  if (time(nullptr) < 1600000000) {
    Serial.println(F("[time] NTP sync failed; countdown will show '--'"));
  } else {
    Serial.printf("[time] UTC epoch %ld\n", (long)time(nullptr));
  }
}

// ---------------------------------------------------------------------------
//  Audio
// ---------------------------------------------------------------------------

// The compiled-in line. Every unit has this one, card or no card, and it is
// what an event without its own clip on the card falls back to. Blocking for
// the length of the clip -- see src/hud_audio.h.
static void playCompiledAlert() {
  audio::playPcm8(audioclip::hellpods, audioclip::kHellpodsLen,
                  audioclip::kSampleRate);
}

// ---------------------------------------------------------------------------
//  Event overlays
// ---------------------------------------------------------------------------

// Raised by poll(), shown by loop(). At most two can come out of a single
// poll -- the outgoing order's verdict and the incoming order's announcement,
// which is the ordinary case when High Command replaces one with the next --
// and they have to be seen in that order, so this is a queue and not a slot.
static OverlayKind overlayQueue[2] = {kOverlayNone, kOverlayNone};
static MajorOrder overlayQueueSubject[2];
static uint8_t overlayQueueLen = 0;

// millis() when the overlay on screen went up, and whether its clip still owes
// a play. Same queue-then-fire discipline as alertPending: sound follows the
// repaint, never leads it.
static uint32_t overlayShownMs = 0;
static bool overlaySoundPending = false;

// How long an overlay waits before giving up on being acknowledged.
//
// Touch is the intended way out and this is a safety net, not a feature: a
// panel that has stopped reading must not be able to strand the HUD on a
// verdict forever. One poll interval is the natural length -- it is the
// "dismiss on the next successful poll" fallback the brief suggested, arrived
// at by the clock instead of by the network, so it holds even if the network
// is also gone.
static const uint32_t kOverlayFallbackMs = (uint32_t)HD2_POLL_INTERVAL_S * 1000UL;

static void queueOverlay(OverlayKind kind, const MajorOrder &subject) {
  if (overlayQueueLen >= 2) return;  // cannot happen; not a reason to corrupt
  overlayQueue[overlayQueueLen] = kind;
  overlayQueueSubject[overlayQueueLen] = subject;
  overlayQueueLen++;
}

static bool allTasksComplete(const MajorOrder &o) {
  if (o.taskCount <= 0) return false;  // nothing to complete is not a success
  for (int i = 0; i < o.taskCount; i++)
    if (!o.tasks[i].complete) return false;
  return true;
}

// Did the order that was on screen just end, and how did it go?
//
// The API has no outcome field and no history endpoint: an assignment that
// ends simply stops being listed. So the verdict is inferred from the last
// state this device saw before it vanished.
//
// `prev` is the outgoing model.order, `next` what this poll returned. This is
// only safe because fetchMajorOrder() failing aborts the poll before here --
// so `next.valid == false` means the API said there is no order, never that
// the request failed. A dropped connection must not read as a lost war.
//
// The brief's two rules overlap on one case: an order whose expiration passes
// with every task done. Read literally, "expiration has passed -> FAILURE"
// would call that a loss. It is plainly a win, so completion is tested first
// and the deadline only decides orders that did not finish.
static OverlayKind classifyOrderOutcome(const MajorOrder &prev, const MajorOrder &next,
                                        time_t nowUtc) {
  if (!prev.valid) return kOverlayNone;

  const bool stillListed = next.valid && next.id == prev.id;
  if (stillListed) {
    // Still on the feed. Only a passed deadline says anything here, and only
    // about an order that has not finished -- a completed one is left alone
    // until it leaves, where it will be read as the success it is.
    const bool expired = prev.expiration > 0 && nowUtc > 1600000000 &&
                         nowUtc >= prev.expiration;
    if (expired && !allTasksComplete(next)) return kOverlayFailure;
    return kOverlayNone;
  }

  // Gone: replaced by a different id, or the feed is empty now.
  return allTasksComplete(prev) ? kOverlaySuccess : kOverlayFailure;
}

// A verdict is announced once. Without this the FAILURE branch above would
// re-fire on every poll for as long as an expired order stayed on the feed,
// and a device left alone overnight would come back to a panel that had been
// shouting at an empty room since 2am.
static int32_t verdictAnnouncedFor = 0;

static storage::Clip overlayClip(OverlayKind k) {
  switch (k) {
    case kOverlaySuccess: return storage::kClipSuccess;
    case kOverlayFailure: return storage::kClipFailure;
    default:              return storage::kClipNewOrder;
  }
}

// The voice for whichever announcement just went up.
//
// The card's clip wins when there is one, because it is specific to this event
// where the compiled-in line is the generic "go look at the screen" -- the
// whole point of the SD card is that the three events stop sounding alike.
// playClip() returns false for no card, no file, or a file this reader will
// not play, and all three land on the same fallback: a unit with no card still
// says something, it just cannot say which thing happened.
static void playOverlayAlert(OverlayKind kind) {
  if (kind == kOverlayNone) return;
  if (!storage::playClip(overlayClip(kind))) playCompiledAlert();
}

// Power-on acknowledgement.
//
// Cody's call, overriding the earlier design here: this plays the same clip
// as a new Major Order announcement (SD card kClipNewOrder, falling back to
// the compiled hellpods line with no card) rather than a distinct chime, so
// every plug-in sounds like the event it is standing in for. An
// update-detected boot below still layers the update alert on top, so that
// remains audible as a second, distinct sound after this one.
static void playBootChime() {
  playOverlayAlert(kOverlayNewOrder);
}

// ---------------------------------------------------------------------------
//  Touch
// ---------------------------------------------------------------------------

// A gesture that landed during the idle wait at the bottom of the previous
// iteration, waiting to be acted on at the top of this one.
static touch::Gesture pendingGesture = touch::kNone;

// Spends `ms` polling the panel instead of sleeping through it.
//
// loop() runs on a 200ms beat, which is generous for a HUD whose data moves
// every five minutes. A swipe is over in two or three hundred milliseconds,
// and a gesture recogniser sampled once per swipe cannot tell where the finger
// started -- it sees one point and calls everything a tap. So the idle time is
// spent reading the panel at the rate hud_touch.cpp expects.
//
// Returns as soon as a gesture completes, cutting the wait short so the
// response lands on the next frame rather than up to 200ms later. That
// difference is the whole distinction between a screen that feels touched and
// one that feels polled.
static touch::Gesture waitWithTouch(uint32_t ms) {
  const uint32_t until = millis() + ms;
  while ((int32_t)(millis() - until) < 0) {
    const touch::Gesture g = touch::poll();
    if (g != touch::kNone) return g;
    delay(5);
  }
  return touch::kNone;
}

// Hold a finger on the panel through power-on to recalibrate it.
//
// Calibration is never run unprompted, not even when none is stored. A desk
// unit is usually powered on by its plug and left alone, and a boot that stops
// for a minute waiting to be touched -- every boot, forever, on any unit whose
// owner never calibrates -- would be a worse bug than a tap landing ten pixels
// out. So it is opt-in, and the log says how at every uncalibrated boot.
//
// The contact has to persist across the sampling window. A single reading
// would be a coin toss: the panel is at its noisiest in the first moments
// after power-up, before the supply has settled.
static void maybeRecalibrateTouch() {
  constexpr uint32_t kHoldMs = 1200;
  constexpr uint8_t kSamples = 12;

  uint8_t seen = 0;
  for (uint8_t i = 0; i < kSamples; i++) {
    if (touch::pressed()) seen++;
    delay(kHoldMs / kSamples);
  }
  // Most, not all: a held finger still drops the odd sample on a resistive
  // panel, and demanding a clean sweep would make the escape hatch itself
  // unreliable -- which is the exact class of problem this is here to fix.
  if (seen < (kSamples * 3) / 4) {
    if (!touch::calibrated()) {
      Serial.println(F("[touch] uncalibrated. To calibrate: hold a finger on the "
                       "panel while powering the board on."));
    }
    return;
  }

  Serial.println(F("[touch] held at boot — diagnostics, then calibration"));
  // Dumped before the calibration rather than after, because if the panel is
  // not reading at all then the four-corner routine is about to sit there
  // doing nothing, and these numbers are what say why.
  touch::dumpDiagnostics(5000);
  touch::calibrate();
  hud.invalidate();
}

// ---------------------------------------------------------------------------
//  Polling
// ---------------------------------------------------------------------------

static void onPollFailed(const char *what) {
  model.failCount++;
  model.stale = true;
  Serial.printf("[poll] FAILED (%s): %s — retry in %us\n", what,
                api.lastError().c_str(), backoffS);
  pollDueMs = millis() + backoffS * 1000UL;
  backoffS = min(backoffS * 2, kBackoffMaxS);
}

// The planet record the last good poll left for `index`, or nullptr. Used to
// ride out a single flaky request without blanking a target card.
static const PlanetInfo *cachedPlanet(int32_t index) {
  for (int i = 0; i < model.order.taskCount; i++) {
    const PlanetInfo &p = model.order.tasks[i].planet;
    if (p.valid && p.index == index) return &p;
  }
  return nullptr;
}

// --- Rate history -----------------------------------------------------------
//
// The card quotes a %-per-hour figure that the API does not publish, so it is
// measured here by keeping one earlier snapshot per target and letting the
// renderer diff it against the live one. Called with `next` fully populated but
// *before* it replaces model.order, which is what makes the old snapshots still
// reachable.
static void rollRateHistory(const MajorOrder &next) {
  // A different order means different targets; anything held over would diff
  // two unrelated planets and invent a swing that never happened.
  if (next.id != model.historyOrderId) {
    for (int i = 0; i < kMaxOrderTasks; i++) model.history[i] = RateSample();
    model.historyOrderId = next.id;
    return;
  }

  for (int i = 0; i < kMaxOrderTasks; i++) {
    RateSample &h = model.history[i];
    if (i >= next.taskCount || !next.tasks[i].planet.valid) {
      h = RateSample();
      continue;
    }
    const PlanetInfo &np = next.tasks[i].planet;
    if (h.planetIndex != np.index) h = RateSample();

    // Advance only when the incoming observation is genuinely newer than the
    // one already on screen. A poll whose planet fetch failed carries the
    // cached snapshot — and its original timestamp — forward unchanged; if that
    // were allowed to shift the history the next good poll would diff a sample
    // against itself and the readout would blink out for no reason.
    const PlanetInfo *prev = cachedPlanet(np.index);
    if (!prev || !prev->valid) continue;
    if (prev->observedAt <= h.at || prev->observedAt >= np.observedAt) continue;

    h.valid = true;
    h.planetIndex = prev->index;
    h.at = prev->observedAt;
    h.libPct = prev->liberation;
    h.haveEvent = prev->event.active;
    h.eventPct = prev->event.defended();
    h.eventEnd = prev->event.endTime;
  }

  // Count-style progress, written after the loop above rather than inside it,
  // and that ordering is the whole point: that loop wipes a sample outright
  // whenever a task's planet cannot be resolved, and a count objective's
  // progress has to outlive exactly that case. It arrives with the assignments
  // payload, so every successful poll has it — while a planet the API holds no
  // record of (it 404s indices missing from its static table, which is the
  // normal state of a newly-added planet) fails on every poll, not one.
  //
  // The previous reading is model.order's, taken at model.lastSuccess: neither
  // has been overwritten yet, same as the planet pass above relies on.
  for (int i = 0; i < kMaxOrderTasks; i++) {
    RateSample &h = model.history[i];
    h.haveCount = false;
    h.countAt = 0;
    h.countPct = 0.0f;

    if (model.lastSuccess <= 0) continue;  // nothing polled yet: no baseline
    if (i >= next.taskCount || i >= model.order.taskCount) continue;
    // Both readings must be the same kind of count for the diff to mean
    // anything -- a task edited in place, or a goal revised mid-order, would
    // otherwise read as a jump in progress that never happened.
    if (!taskIsCount(next.tasks[i]) || !taskIsCount(model.order.tasks[i])) continue;
    if (next.tasks[i].taskType != model.order.tasks[i].taskType) continue;
    if (next.tasks[i].goal != model.order.tasks[i].goal) continue;

    h.haveCount = true;
    h.countAt = model.lastSuccess;
    h.countPct = taskPercent(model.order.tasks[i]);
  }
}

// Same invariant as rollRateHistory() above — only advance a sample when the
// incoming observation is genuinely newer, reset rather than diff across a
// different planet — but matched by planet index rather than array position:
// the campaigns list is top-N by player count, so which planet sits in slot i
// can reshuffle poll to poll (a planet dropping out of the top N and a
// different one taking its slot included). Called with `next` fully
// populated but before it replaces model.campaigns, same as above.
static void rollCampaignHistory(const PlanetInfo next[], int nextCount) {
  RateSample nextHistory[kMaxCampaigns];

  for (int i = 0; i < nextCount; i++) {
    RateSample h;
    const PlanetInfo *prev = nullptr;
    for (int j = 0; j < model.campaignCount; j++) {
      if (model.campaigns[j].valid && model.campaigns[j].index == next[i].index) {
        prev = &model.campaigns[j];
        h = model.campaignHistory[j];
        break;
      }
    }
    if (h.planetIndex != next[i].index) h = RateSample();

    if (prev && prev->valid && prev->observedAt > h.at &&
        prev->observedAt < next[i].observedAt) {
      h.valid = true;
      h.planetIndex = prev->index;
      h.at = prev->observedAt;
      h.libPct = prev->liberation;
    }
    nextHistory[i] = h;
  }

  for (int i = 0; i < nextCount; i++) model.campaignHistory[i] = nextHistory[i];
  for (int i = nextCount; i < kMaxCampaigns; i++) model.campaignHistory[i] = RateSample();
}

static void poll() {
  if (WiFi.status() != WL_CONNECTED) {
    onPollFailed("wifi down");
    return;
  }

  Serial.println(F("[poll] fetching assignments"));
  MajorOrder order;
  if (!api.fetchMajorOrder(order)) {
    onPollFailed("assignments");
    return;
  }

  // An empty assignments array is a valid state, not a failure: it just means
  // there is no Major Order right now. order.valid stays false and the HUD
  // shows the idle screen.
  //
  // One lookup per task: a "defend three planets" order names three different
  // planets and dropping all but the first is exactly the bug this loop
  // exists to avoid. kInterRequestDelayMs is sized for the resulting burst.
  if (order.valid) {
    for (int i = 0; i < order.taskCount; i++) {
      OrderTask &t = order.tasks[i];
      if (t.planetIndex < 0) continue;  // galaxy-wide objective, nothing to fetch

      delay(kInterRequestDelayMs);
      Serial.printf("[poll] fetching planet %d (task %d/%d, type %d)\n",
                    (int)t.planetIndex, i + 1, order.taskCount, (int)t.taskType);
      if (api.fetchPlanet(t.planetIndex, t.planet)) {
        // Time-base for the %-per-hour readouts. Left at 0 until NTP has landed
        // so a pre-sync boot cannot stamp a sample with a 1970 date.
        const time_t now = time(nullptr);
        if (now > 1600000000) t.planet.observedAt = now;
      } else {
        Serial.printf("[poll] planet lookup failed: %s\n", api.lastError().c_str());
        // The cached record is copied whole, timestamp included, so it stays
        // honestly dated as the older observation it is.
        const PlanetInfo *prev = cachedPlanet(t.planetIndex);
        if (prev) t.planet = *prev;
      }
    }
  }

  // With no Major Order there is no task list and therefore no planet, so the
  // screen would have nothing on it but a placeholder. The campaigns feed
  // fills the carousel instead. An active order owns the screen outright, so
  // this costs a request only in the state that would otherwise be idle and
  // the steady-state budget is unchanged.
  PlanetInfo campaigns[kMaxCampaigns];
  int campaignCount = 0;
  if (!order.valid) {
    delay(kInterRequestDelayMs);
    Serial.println(F("[poll] no order — fetching campaigns"));
    if (api.fetchCampaigns(campaigns, kMaxCampaigns, campaignCount)) {
      const time_t now = time(nullptr);
      for (int i = 0; i < campaignCount; i++) {
        if (now > 1600000000) campaigns[i].observedAt = now;
      }
      Serial.printf("[poll] campaigns: %d found, top %s at %.2f%% lib, %u divers\n",
                    campaignCount, campaignCount ? campaigns[0].name.c_str() : "n/a",
                    campaignCount ? campaigns[0].liberation : 0.0f,
                    campaignCount ? (unsigned)campaigns[0].playerCount : 0U);
    } else {
      // Not an error: a quiet galaxy, or the fetch failed. Either way the
      // previous set is better than blanking the screen.
      Serial.printf("[poll] campaigns lookup: %s\n", api.lastError().c_str());
      campaignCount = model.campaignCount;
      for (int i = 0; i < campaignCount; i++) campaigns[i] = model.campaigns[i];
    }
  }

  // War stats are garnish — a failure here never fails the poll, and we keep
  // whatever we had before.
  delay(kInterRequestDelayMs);
  WarStats war;
  if (!api.fetchWar(war)) {
    Serial.printf("[poll] war stats failed: %s\n", api.lastError().c_str());
    war = model.war;
  }

  // A Major Order this device has not seen before. Gated on haveData so the
  // first poll after a power cycle stays quiet -- the order that was already
  // running when the board booted is not news, and without this every outage
  // and every reboot would announce itself.
  const bool orderIsNew = order.valid && model.haveData && order.id != model.order.id;

  // How the outgoing order ended, if it did. Gated on haveData for the same
  // reason as orderIsNew: on the first poll after a reboot there is no
  // "before" to compare against, and an empty model.order would otherwise be
  // read as an order that vanished.
  //
  // Deliberately evaluated here, against model.order, before the assignment
  // below overwrites it.
  if (model.haveData) {
    const OverlayKind verdict =
        classifyOrderOutcome(model.order, order, time(nullptr));
    if (verdict != kOverlayNone && verdictAnnouncedFor != model.order.id) {
      verdictAnnouncedFor = model.order.id;
      Serial.printf("[order] %d \"%s\" -> %s\n", (int)model.order.id,
                    model.order.title.c_str(),
                    verdict == kOverlaySuccess ? "SUCCESS" : "FAILURE");
      queueOverlay(verdict, model.order);
    }
  }

  // Both read the *outgoing* model.order/model.campaigns, so they have to run
  // before those are overwritten below.
  rollRateHistory(order);
  rollCampaignHistory(campaigns, campaignCount);

  for (int i = 0; i < campaignCount; i++) model.campaigns[i] = campaigns[i];
  for (int i = campaignCount; i < kMaxCampaigns; i++) model.campaigns[i] = PlanetInfo();
  model.campaignCount = (uint8_t)campaignCount;
  model.order = order;
  model.war = war;
  model.haveData = true;
  model.stale = false;
  model.failCount = 0;
  model.lastSuccess = time(nullptr);

  backoffS = kBackoffMinS;
  pollDueMs = millis() + (uint32_t)HD2_POLL_INTERVAL_S * 1000UL;

  if (order.valid) {
    Serial.printf("[poll] OK — \"%s\", %d target(s), heap %u\n", order.title.c_str(),
                  order.taskCount, (unsigned)ESP.getFreeHeap());
    for (int i = 0; i < order.taskCount; i++) {
      const OrderTask &t = order.tasks[i];
      // Liberation is only quoted for the task type it means something for.
      if (t.planet.valid && t.planet.event.active) {
        Serial.printf("  [%d] type %d  %s  %.4f%% defended vs %s (%u hazard(s))\n",
                      i + 1, (int)t.taskType, t.planet.name.c_str(),
                      t.planet.event.defended(), t.planet.event.faction.c_str(),
                      (unsigned)t.planet.hazardCount);
      } else if (taskIsLiberation(t.taskType) && t.planet.valid) {
        Serial.printf("  [%d] type %d  %s  %.1f%% liberated\n", i + 1, (int)t.taskType,
                      t.planet.name.c_str(), t.planet.liberation);
      } else {
        Serial.printf("  [%d] type %d  %s  %s (owner %s)\n", i + 1, (int)t.taskType,
                      t.planet.valid ? t.planet.name.c_str() : "n/a",
                      t.complete ? "complete" : "incomplete",
                      t.planet.valid ? t.planet.owner.c_str() : "?");
      }
    }
  } else {
    Serial.printf("[poll] OK — no active Major Order, heap %u\n",
                  (unsigned)ESP.getFreeHeap());
  }

  // Queued rather than shown here: poll() runs before the frame that draws
  // this order, and an alert that finishes while the panel still shows the
  // previous one has told you to look at the wrong thing. loop() raises the
  // overlay and fires its clip once the repaint has landed.
  if (orderIsNew) {
    Serial.printf("[order] new Major Order %d — \"%s\"\n", (int)order.id,
                  order.title.c_str());
    queueOverlay(kOverlayNewOrder, order);
  }
}

// ---------------------------------------------------------------------------
//  Setup / loop
// ---------------------------------------------------------------------------

void setup() {
  Serial.begin(115200);
  delay(200);
  Serial.println(F("\n=== HD2 Major Order Monitor ==="));
  // Stamped from `git describe` by tools/fw_version.py. Deliberately not
  // guarded by an #ifndef: a build that somehow loses the flag should fail to
  // compile rather than quietly ship an image that lies about its version.
  Serial.printf("[boot] firmware %s\n", HD2_FW_VERSION);

  hud.begin();
  audio::begin();
  // Before the first sound is played, so a card that is present is already
  // usable by the boot chime's successors. A missing card is logged and
  // ignored -- every unit in the field today has an empty slot, and none of
  // them may be worse off for this firmware.
  storage::begin();
  touch::begin(hud.panel());
  maybeRecalibrateTouch();
  hud.showBoot("Connecting to WiFi...");

  // "I'm awake." Every boot, power-cycle included, once the panel is lit and
  // the amp is configured -- so the sound never arrives before there is
  // anything on screen to look at. Unconditional, including the first-ever
  // boot: unlike the update alert below, this is confirmation that power
  // reached the board, which is exactly what a fresh unit's owner wants.
  playBootChime();

  // Displayed clock times are UTC + this. Persisted in NVS alongside (but
  // separately from) the WiFi credentials, so it survives reflashing and is
  // set without recompiling.
  prefs.begin(HD2_PREFS_NS, false);

  // --- "the board was updated" ----------------------------------------------
  // An OTA reboots into the new image, so the update itself is never a moment
  // this code is running for -- the *next* boot is. Comparing the running
  // version against the one the last boot recorded is what makes that
  // detectable, and it covers a USB reflash the same way.
  //
  // A first-ever boot has nothing stored and stays silent: a device fresh out
  // of the box has not been updated, it has been set up, and announcing that
  // to an empty room is just noise.
  {
    const String ranBefore = prefs.getString(HD2_PREFS_FW_KEY, String());
    const String running = String(HD2_FW_VERSION);
    if (ranBefore.length() && ranBefore != running) {
      Serial.printf("[audio] updated %s -> %s\n", ranBefore.c_str(), running.c_str());
      playCompiledAlert();
    }
    if (ranBefore != running) prefs.putString(HD2_PREFS_FW_KEY, running);
  }

  model.utcOffsetMin =
      (int16_t)prefs.getShort(HD2_PREFS_TZ_KEY, kUtcOffsetMinutesDefault);
  char offsetField[10];
  formatUtcOffset(model.utcOffsetMin, offsetField, sizeof(offsetField));
  Serial.printf("[time] display offset %s (%d min from UTC)\n", offsetField,
                (int)model.utcOffsetMin);

  WiFiManager wm;
  wm.setDebugOutput(false);
  // Bounded so an unattended desk unit reboots and retries rather than sitting
  // in the config portal forever after a router outage.
  wm.setConfigPortalTimeout(kPortalTimeoutS);
  wm.setAPCallback([](WiFiManager *) { hud.showPortal(kPortalSsid, kPortalPass); });

  // Extra field on the portal page, under the network picker. It must outlive
  // autoConnect(), which is why it is declared here and not in a helper.
  WiFiManagerParameter offsetParam(
      "utcoff", "UTC offset in hours (e.g. -6, +1, +5:30)", offsetField,
      sizeof(offsetField) - 1);
  wm.addParameter(&offsetParam);

  if (!wm.autoConnect(kPortalSsid, kPortalPass)) {
    Serial.println(F("[wifi] portal timed out — rebooting"));
    hud.showBoot("Setup timed out. Restarting...");
    delay(2000);
    ESP.restart();
  }

  Serial.printf("[wifi] connected to %s as %s\n", WiFi.SSID().c_str(),
                WiFi.localIP().toString().c_str());
  WiFi.setAutoReconnect(true);
  WiFi.persistent(true);

  // If the portal ran, the field holds whatever was typed; if it didn't, it
  // still holds the value we pre-filled, so this is a no-op on a normal boot.
  // A value that doesn't parse is ignored rather than reset to UTC, so a typo
  // can't silently wipe a good setting.
  int16_t typed = 0;
  if (parseUtcOffset(offsetParam.getValue(), typed)) {
    if (typed != model.utcOffsetMin) {
      model.utcOffsetMin = typed;
      prefs.putShort(HD2_PREFS_TZ_KEY, typed);
      Serial.printf("[time] display offset saved: %d min from UTC\n", (int)typed);
    }
  } else {
    Serial.printf("[time] ignoring unparseable UTC offset \"%s\"; keeping %d min\n",
                  offsetParam.getValue(), (int)model.utcOffsetMin);
  }

  hud.showBoot("Synchronising clock...");
  syncClock();

  hud.showBoot("Contacting High Command...");
  hud.invalidate();

  // Downloading and flashing an image takes minutes and paints over the HUD,
  // which from the desk is indistinguishable from a crash unless the screen
  // says otherwise. Invalidating right here rather than after the update
  // covers the failure path too: if the flash fails the loop keeps running
  // with the notice still on the panel, and the renderer would otherwise see
  // an unchanged model and leave it there.
  ota.onUpdateStarting([](const char *message) {
    hud.showBoot(message);
    hud.invalidate();
  });
  ota.begin();

  pollDueMs = millis();  // poll immediately
}

void loop() {
  const uint32_t nowMs = millis();
  model.wifiUp = (WiFi.status() == WL_CONNECTED);

  // Nudge the WiFi stack if it has dropped. autoReconnect usually handles it;
  // this covers the cases where it gives up.
  if (!model.wifiUp && (int32_t)(nowMs - wifiRetryDueMs) >= 0) {
    Serial.println(F("[wifi] disconnected — reconnecting"));
    WiFi.reconnect();
    wifiRetryDueMs = nowMs + 15000;
  }

  if ((int32_t)(nowMs - pollDueMs) >= 0) poll();

  // Own timer, an hour apart, and a no-op on every iteration but those. It is
  // deliberately after the poll: the two share the device's one TLS connection
  // budget, and on the rare tick where both are due, data on screen matters
  // more than firmware freshness. A successful update never returns from here.
  ota.tick(model.wifiUp);

  const time_t nowUtc = time(nullptr);

  // Stale if the last poll failed, or if we simply haven't heard anything in
  // a couple of poll intervals (e.g. the ESP is up but the network isn't).
  if (model.haveData) {
    model.stale = (model.failCount > 0) ||
                  (nowUtc > 1600000000 && model.lastSuccess > 0 &&
                   (uint32_t)(nowUtc - model.lastSuccess) > kStaleAfterS);
  }

  // --- touch ---------------------------------------------------------------
  //
  // Usually the gesture already arrived, during the polling wait that ended
  // the last iteration. The direct poll() covers the rest of the beat -- a
  // contact that finished while this iteration was fetching or repainting.
  touch::Gesture gesture = pendingGesture;
  pendingGesture = touch::kNone;
  if (gesture == touch::kNone) gesture = touch::poll();

  if (model.overlay != kOverlayNone) {
    // Any contact dismisses. A tap is the documented gesture, but a swipe
    // aimed at a screen that has taken the whole panel means the same thing,
    // and refusing it would only read as the touch being broken.
    const bool acknowledged = (gesture != touch::kNone);
    const bool timedOut = (uint32_t)(nowMs - overlayShownMs) >= kOverlayFallbackMs;
    if (acknowledged || timedOut) {
      Serial.printf("[overlay] dismissed by %s\n", acknowledged ? "touch" : "timeout");
      const bool wasNewOrder = (model.overlay == kOverlayNewOrder);
      model.overlay = kOverlayNone;
      // Hand back to the new order's first objective rather than to wherever
      // the carousel had got to before the announcement interrupted it.
      if (wasNewOrder) hud.resetCarousel();
    }
  } else if (gesture == touch::kSwipeLeft) {
    hud.advancePage(model, +1);
  } else if (gesture == touch::kSwipeRight) {
    hud.advancePage(model, -1);
  }

  // --- overlays ------------------------------------------------------------
  //
  // Raised here rather than in poll() so an announcement goes up on a frame of
  // its own, after the model behind it has settled.
  //
  // After the dismissal check above, deliberately. Draining the queue first
  // would let one gesture clear an announcement and the one behind it in the
  // same iteration -- the second would be acknowledged before it was ever
  // drawn. Each one gets its own frame and its own dismissal.
  if (model.overlay == kOverlayNone && overlayQueueLen > 0) {
    model.overlay = overlayQueue[0];
    model.overlaySubject = overlayQueueSubject[0];
    overlayQueue[0] = overlayQueue[1];
    overlayQueueSubject[0] = overlayQueueSubject[1];
    overlayQueueLen--;
    overlayShownMs = nowMs;
    overlaySoundPending = true;
  }

  hud.update(model, nowUtc);

  // Sound follows the frame, always. Playback blocks for the length of the
  // clip, so firing before the repaint would announce a screen that is not on
  // the panel yet -- the same reason the new-order alert was queued before
  // there were overlays to queue with it.
  if (overlaySoundPending) {
    overlaySoundPending = false;
    playOverlayAlert(model.overlay);
  }

  pendingGesture = waitWithTouch(200);
}
